### ISSUE TITLE
1.4.0 operator install results in operator-webhook with failed readiness probe

### ISSUE THREAD

**Issue by davesargrad** [knative/operator#1068]
I've followed the instructions for installing knative via operator. Though the knative-operator is running
`knative-operator-df4cf6b69-759dd               1/1     Running     0             4m7s`
The operator-webhook is restarting and not ready
`operator-webhook-869bd85fd6-mrh9r              0/1     Running     3 (3s ago)    4m7s`

When I describe the pod:
```
[admin@sdie-2-pm-4 ~]$ k describe pod operator-webhook-869bd85fd6-mrh9r
Name:         operator-webhook-869bd85fd6-mrh9r
Namespace:    default
Priority:     0
Node:         sdie-2-pm-8/10.92.82.80
Start Time:   Tue, 10 May 2022 10:30:55 -0400
Labels:       app=operator-webhook
              app.kubernetes.io/component=operator-webhook
              app.kubernetes.io/name=knative-operator
              app.kubernetes.io/version=1.4.0
              operator.knative.dev/release=v1.4.0
              pod-template-hash=869bd85fd6
              role=operator-webhook
Annotations:  cluster-autoscaler.kubernetes.io/safe-to-evict: false
Status:       Running
IP:           10.42.7.157
IPs:
  IP:           10.42.7.157
Controlled By:  ReplicaSet/operator-webhook-869bd85fd6
Containers:
  operator-webhook:
    Container ID:   containerd://0292ab46eee1670e2f923e10986b4372cb4509be81e861a95d78d9a1d972c738
    Image:          gcr.io/knative-releases/knative.dev/operator/cmd/webhook@sha256:d3a7da7499b84f334567eb54be248ca7a90e2de9aab60a24f0c6815911022d10
    Image ID:       gcr.io/knative-releases/knative.dev/operator/cmd/webhook@sha256:d3a7da7499b84f334567eb54be248ca7a90e2de9aab60a24f0c6815911022d10
    Ports:          9090/TCP, 8008/TCP, 8443/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Tue, 10 May 2022 10:36:46 -0400
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 10 May 2022 10:35:36 -0400
      Finished:     Tue, 10 May 2022 10:36:46 -0400
    Ready:          False
    Restart Count:  5
    Limits:
      cpu:     500m
      memory:  500Mi
    Requests:
      cpu:      100m
      memory:   100Mi
    Liveness:   http-get https://:8443/ delay=20s timeout=1s period=1s #success=1 #failure=6
    Readiness:  http-get https://:8443/ delay=0s timeout=1s period=1s #success=1 #failure=3
    Environment:
      POD_NAME:                   operator-webhook-869bd85fd6-mrh9r (v1:metadata.name)
      SYSTEM_NAMESPACE:           default (v1:metadata.namespace)
      CONFIG_LOGGING_NAME:        config-logging
      CONFIG_OBSERVABILITY_NAME:  config-observability
      WEBHOOK_NAME:               operator-webhook
      WEBHOOK_PORT:               8443
      METRICS_DOMAIN:             knative.dev/operator
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xl7t4 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-xl7t4:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  5m57s                  default-scheduler  Successfully assigned default/operator-webhook-869bd85fd6-mrh9r to sdie-2-pm-8
  Normal   Pulled     5m24s                  kubelet            Container image "gcr.io/knative-releases/knative.dev/operator/cmd/webhook@sha256:d3a7da7499b84f334567eb54be248ca7a90e2de9aab60a24f0c6815911022d10" already present on machine
  Normal   Created    5m24s                  kubelet            Created container operator-webhook
  Normal   Started    5m24s                  kubelet            Started container operator-webhook
  Warning  Unhealthy  24s (x314 over 5m24s)  kubelet            Readiness probe failed: Get "https://10.42.7.157:8443/": remote error: tls: unrecognized name

```

**Comment by davesargrad** [comment]
I see 5 references to 8443 in the referenced yaml,
kubectl apply -f https://github.com/knative/operator/releases/download/knative-v1.4.0/operator.yaml
Should I change these all to an available port?

**Comment by davesargrad** [comment]
When I diff my operator.yaml against the one provided in instructions, I see the 5 changes. However I  also see 443 as the port for the https-webhook.. did I make the proper change to the yaml?
![image](https://user-images.githubusercontent.com/48793689/167664291-6c422658-bcbd-424e-8098-5466300c67e8.png)

**Comment by houshengbo** [comment]
I am not sure if this issue is related to https://github.com/knative/operator/issues/1007.
If there is an issue with the webhook. You need to focus on the deployment of the operator-webhook:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-webhook
  namespace: default
  labels:
    operator.knative.dev/release: devel
    app.kubernetes.io/component: operator-webhook
    app.kubernetes.io/version: devel
    app.kubernetes.io/name: knative-operator
spec:
  selector:
    matchLabels:
      app: operator-webhook
      role: operator-webhook
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        sidecar.istio.io/inject: "false"
      labels:
        app: operator-webhook
        role: operator-webhook
        operator.knative.dev/release: devel
        app.kubernetes.io/component: operator-webhook
        app.kubernetes.io/version: devel
        app.kubernetes.io/name: knative-operator
    spec:
      # To avoid node becoming SPOF, spread our replicas to different nodes.
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: webhook
              topologyKey: kubernetes.io/hostname
            weight: 100

      serviceAccountName: operator-webhook
      containers:
      - name: operator-webhook
        # This is the Go import path for the binary that is containerized
        # and substituted here.
        image: ko://knative.dev/operator/cmd/webhook

        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi

        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: WEBHOOK_NAME
          value: operator-webhook
        - name: WEBHOOK_PORT
          value: "8443"

        - name: METRICS_DOMAIN
          value: knative.dev/operator

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - all

        ports:
        - name: metrics
          containerPort: 9090
        - name: profiling
          containerPort: 8008
        - name: https-webhook
          containerPort: 8443

        readinessProbe:
          periodSeconds: 1
          httpGet:
            scheme: HTTPS
            port: 8443
            httpHeaders:
            - name: k-kubelet-probe
              value: "webhook"
        livenessProbe:
          periodSeconds: 1
          httpGet:
            scheme: HTTPS
            port: 8443
            httpHeaders:
            - name: k-kubelet-probe
              value: "webhook"
          failureThreshold: 6
          initialDelaySeconds: 20

      # Our webhook should gracefully terminate by lame ducking first, set this to a sufficiently
      # high value that we respect whatever value it has configured for the lame duck grace period.
      terminationGracePeriodSeconds: 300
```

And there is a service connecting to the deployment:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    role: operator-webhook
    operator.knative.dev/release: devel
    app.kubernetes.io/component: operator-webhook
    app.kubernetes.io/version: devel
    app.kubernetes.io/name: knative-operator
  name: operator-webhook
  namespace: default
spec:
  ports:
    # Define metrics and profiling for them to be accessible within service meshes.
    - name: http-metrics
      port: 9090
      targetPort: 9090
    - name: http-profiling
      port: 8008
      targetPort: 8008
    - name: https-webhook
      port: 443
      targetPort: 8443
  selector:
    role: operator-webhook
```

The secret is created as well:
```
apiVersion: v1
kind: Secret
metadata:
  name: operator-webhook-certs
  namespace: default
  labels:
    app.kubernetes.io/component: webhook
    operator.knative.dev/release: devel
    app.kubernetes.io/version: devel
    app.kubernetes.io/part-of: knative-operator
```
