### ISSUE TITLE
KnativeServing deployment fails when specifying resources

### ISSUE THREAD

**Issue by nickzelei** [knative/operator#1094]
**Describe the bug**
I'm unable to create `KnativeServing` when specifying the `resources` property in `spec`.
Commenting out the resources resulted in a successful apply.
I last did this against operator `v1.1.0` against the v1alpha1 spec just fine. I followed the guidelines listed here: https://knative.dev/docs/install/operator/configuring-serving-cr/#system-resource-settings

```
error: error validating "STDIN": error validating data: ValidationError(KnativeServing.spec): unknown field "resources" in dev.knative.operator.v1beta1.KnativeServing.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

**Expected behavior**
KnativeServing should be able to be properly created with resource constraints.

**To Reproduce**
Run this Yaml:
```
# Auto-tls https://knative.dev/docs/serving/using-auto-tls/
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
spec:
  ingress:
    kourier:
      enabled: true
  config:
    network:
      ingress-class: 'kourier.ingress.networking.knative.dev'
      # Enables certificates for all namespaces except those with the networking.knative.dev/disableWildcardCert: true label,
      'namespace-wildcard-cert-selector': '{"matchExpressions": [{"key":"networking.knative.dev/disableWildcardCert", "operator": "NotIn", "values":["true"]}]}'
      # This was unable to be done as a separate patch. Kustomize kept complaining that it couldn't find the config /shrug
      'auto-tls': Enabled
      'http-protocol': Redirected
    domain:
      '<my-domain>': ''
    gc:
      # Duration since creation before considering a revision for GC or \"disabled\".
      'retain-since-create-time': 'disabled'

      # Duration since active before considering a revision for GC or \"disabled\".
      'retain-since-last-active-time': 'disabled'

      # Minimum number of non-active revisions to retain.
      'min-non-active-revisions': '0'

      # Maximum number of non-active revisions to retain
      # or \"disabled\" to disable any maximum limit.
      'max-non-active-revisions': '0'
  resources:
    - container: activator
      requests:
        cpu: 25m
        memory: 50Mi
      limits:
        cpu: 25m
        memory: 250Mi
        ephemeral-storage: 50Mi
    - container: autoscaler
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 300m
        memory: 250Mi
        ephemeral-storage: 50Mi
    - container: domainmapping-webhook
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 250Mi
        ephemeral-storage: 50Mi
    - container: webhook
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 250Mi
        ephemeral-storage: 50Mi
    - container: controller
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 250Mi
        ephemeral-storage: 50Mi
    - container: autoscaler-hpa
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 250Mi
        ephemeral-storage: 50Mi
```

**Knative release version**
Latest (unspecified in yaml)

**Additional context**

knative operator was installed with the latest version using:
`https://github.com/knative/operator/releases/download/knative-v1.4.1/operator.yaml`
I'm also using net-certmanager along with cert-manager for auto-tls using `https://github.com/knative/net-certmanager/releases/download/knative-v1.5.0/release.yaml`

**Comment by houshengbo** [comment]
@nickzelei I am sorry for the inconsistency in the docs of 1.4.
For operator, there are two CRD versions: v1alpha1 and v1beta1.
I think the syntax you used still works in v1alpha1, but NOT in v1beta1 any more.

In v1beta1, you need to specify the deployments as the parent of resources, like:
```
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    kourier:
      enabled: true
  config:
    network:
      ingress-class: 'kourier.ingress.networking.knative.dev'
  deployments:
  - name: activator
    resources:
    - container: activator
      requests:
        cpu: 25m
        memory: 50Mi
      limits:
        cpu: 25m
        memory: 250Mi
```
