### ISSUE TITLE
Operator is installing a deprecated KafkaSource

### ISSUE THREAD

**Issue by pierDipi** [knative/operator#1212]
**Describe the bug**

The operator is installing the deprecated `KafkaSource` from `eventing-kafka`, the new source is hosted in `eventing-kafka-broker`.

**Expected behavior**

The old source is replaced with the new one.

**To Reproduce**

Enable Kafka source using the operator API.

**Knative release version**

> 1.6.*

**Additional context**
Add any other context about the problem here such as proposed priority

**Comment by houshengbo** [comment]
@pierDipi What version is the last version we use eventing-kafka?
What version is the first version to use eventing-kafka-broker?
I need to change the fetcher to reflect the changes.

**Comment by pierDipi** [comment]
Hey Vincent, the version is 1.6 and 1.7 for eventing-kafka-broker.

The files needed are listed here: https://knative.dev/docs/eventing/sources/kafka-source/#installing-kafka-source

In addition, the operator should apply the post-install artifact that is released in eventing-kafka-broker, it provided automatic migration from the old source to the new one.

**Comment by houshengbo** [comment]
I need to ask @evankanderson to see if the fetcher can handle different repo for the same eventing sources across different versions.

**Comment by evankanderson** [comment]
You should be able to (ab)use the `override` feature feature for this. I added it because the early-on eventing releases weren't really set up for automatic consumption by machines.

See [this example of `overrides` from the first commit]( https://github.com/knative/operator/blob/fd53bd554e19788c081861f1c9206e059a7c053c/cmd/fetcher/kodata/config.yaml#L28)

Try:
```
eventing-source:
  alternatives: true
  ...
  additional:
    ...
    - s3:
        bucket: "gs-noauth://knative-releases"
        prefix: "eventing-kafka/previous"
      eventingService: "kafka"
      include:
       - "^source.yaml"
      overrides:
         v1.7:
           include: []
    - s3:
        bucket: "gs-noauth://knative-releases"
        prefix: "eventing-kafka-broker/previous"
      eventingService: "kafka"
      include:
       - "eventing-kafka-source.yaml"
      overrides:
         v1.6:
           include: []
         v1.5:
           include: []
         v1.4:
           include: []
```
