### ISSUE TITLE
Can not scale unused components to replicas zero

### ISSUE THREAD

**Issue by matzew** [knative/operator#1223]
Let's assume there is zero interest in using the `MTChannelBroker` and the `InMemoryChannel`, because I am only interested in the `KafkaChannel` and the `KafkaSource`.

In that case, in order to safe resources, I'd like to set the replica for all unused components to `0`, like:

```yaml
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  deployments:
  - name: imc-controller
    replicas: 0
  - name: imc-dispatcher
    replicas: 0
  - name: mt-broker-controller
    replicas: 0
  - name: mt-broker-filter
    replicas: 0
  - name: mt-broker-ingress
    replicas: 0
```

But this is not possible:

```
The KnativeEventing "knative-eventing" is invalid: 
* spec.deployments[0].replicas: Invalid value: 0: spec.deployments[0].replicas in body should be greater than or equal to 1
* spec.deployments[1].replicas: Invalid value: 0: spec.deployments[1].replicas in body should be greater than or equal to 1
* spec.deployments[2].replicas: Invalid value: 0: spec.deployments[2].replicas in body should be greater than or equal to 1
* spec.deployments[3].replicas: Invalid value: 0: spec.deployments[3].replicas in body should be greater than or equal to 1
* spec.deployments[4].replicas: Invalid value: 0: spec.deployments[4].replicas in body should be greater than or equal to 1
```

**Comment by matzew** [comment]
Doing a different configuration to just get the `eventing-controller` and `eventing-webhook`, like:

```yaml
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  high-availability:
    replicas: 0
  deployments:
  - name: eventing-controller
    replicas: 1
  - name: eventing-webhook
    replicas: 1
```

Gives me the same/similar error:

```
The KnativeEventing "knative-eventing" is invalid: spec.high-availability.replicas: Invalid value: 0: spec.high-availability.replicas in body should be greater than or equal to 1
```
