### ISSUE TITLE
Unable to install Knative-Serving via Operator without istio

### ISSUE THREAD

**Issue by MaharaJothi** [knative/operator#1241]
**Describe the bug**
I installed Knative operator using below command:
`kubectl apply -f https://github.com/knative/operator/releases/download/knative-v1.7.0/operator.yaml`

Tried installing Knative-Serving component but it fails with below error:
YAML:
```
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    domain:
      "test.knative.cloud": ""
    network:
      ingress-class: "kong-ingress"
```
Output:
```
NAME              VERSION   READY   REASON
knative-serving             False   Error
```

`please install istio or disable the istio ingress plugin: no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"`

I want to use Kong gateway for ingress so I do not have Istio installed in my cluster.  
How can I disable the default behavior where it expects istio?

**Expected behavior**
Knative-Serving should get installed successfully.

**To Reproduce**
Install knative-operator followed by knative-serving component in a cluster which doesn't have Istio.

**Knative release version**
1.7.0
