### ISSUE TITLE
Please Support net-gateway-api

### ISSUE THREAD

**Issue by kahirokunn** [knative/operator#1285]
Currently there is no entry for `gateway-api` in IngressConfigs.
It would be great if you could support `net-gateway-api` when it graduates from the sandbox!

https://github.com/knative/operator/blob/de589bd2697d6bab4e04a3d376baff84ae2e40de/pkg/apis/operator/v1beta1/knativeserving_types.go#L85
https://github.com/knative-sandbox/net-gateway-api

**Comment by kahirokunn** [comment]
> Like is it just a new option to configure the knative serving to use gateway API

I am considering this one first.

> There are tons of ingresses that support gateway api, how can we configure each of them as the ingress of knative serving?

I don't think it is necessary to consider which Ingress supports the Gateway API.
We believe it is sufficient to support the provision of HTTPRoute and gRPCRoute in the format supported by the standard Gateway API.
It is better for users to build their own Ingress that supports the Gateway API.
By the way, I would like to integrate cilium's Gateway API.

**Comment by kahirokunn** [comment]
@houshengbo Sorry for the late reply.

**Comment by kahirokunn** [comment]
Keep

**Comment by kahirokunn** [comment]
keep

**Comment by kahirokunn** [comment]
@houshengbo 

1. allow config-gateway configuration
2. install net-gateway-api
This is all that is required.
I don't think we need to provide the details for each vendor.
For example, in the case of Cilium, it is as follows.

```yaml
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
spec:
  config:
    gateway:
      external-gateways: |
        - class: cilium
          gateway: knative-external-gateway/knative
          service: knative-external-gateway/cilium-gateway-knative
          supported-features:
          - Gateway
          - GatewayPort8080
          - GatewayStaticAddresses
          - HTTPRoute
          - HTTPRouteDestinationPortMatching
          - HTTPRouteHostRewrite
          - HTTPRouteMethodMatching
          - HTTPRoutePathRedirect
          - HTTPRoutePathRewrite
          - HTTPRoutePortRedirect
          - HTTPRouteQueryParamMatching
          - HTTPRouteRequestMirror
          - HTTPRouteRequestMultipleMirrors
          - HTTPRouteResponseHeaderModification
          - HTTPRouteSchemeRedirect
          - Mesh
          - ReferenceGrant
          - TLSRoute
      local-gateways: |
        - class: cilium
          gateway: knative-local-gateway/knative
          service: knative-local-gateway/cilium-gateway-knative
          supported-features:
          - Gateway
          - GatewayPort8080
          - GatewayStaticAddresses
          - HTTPRoute
          - HTTPRouteDestinationPortMatching
          - HTTPRouteHostRewrite
          - HTTPRouteMethodMatching
          - HTTPRoutePathRedirect
          - HTTPRoutePathRewrite
          - HTTPRoutePortRedirect
          - HTTPRouteQueryParamMatching
          - HTTPRouteRequestMirror
          - HTTPRouteRequestMultipleMirrors
          - HTTPRouteResponseHeaderModification
          - HTTPRouteSchemeRedirect
          - Mesh
          - ReferenceGrant
          - TLSRoute
    network:
      ingress-class: gateway-api.ingress.networking.knative.dev
```
