### ISSUE TITLE
Updating Activator's `terminationGracePeriodSeconds` value

### ISSUE THREAD

**Issue by psschwei** [knative/operator#1295]
Hello everyone.

I am also interested in setting `max-revision-timeout-seconds` to a larger value. However I can't find how to update the `terminationGracePeriod` in activator.

From @mkyrilov 's [comment](https://github.com/knative/serving/issues/12564#issuecomment-1343317818) in Serving:

I am using the operator to install Knative Serving:

```yaml
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: 1.8.0 # Same version as the operator
  config:
    defaults:
      max-revision-timeout-seconds: "7200" # 120 minutes
    domain:
      kn.example.com: "" # your DNS
    features:
      kubernetes.podspec-persistent-volume-claim: "enabled"
      kubernetes.podspec-persistent-volume-write: "enabled"
      kubernetes.podspec-affinity: "enabled"
      kubernetes.podspec-tolerations: "enabled"
      kubernetes.podspec-init-containers: "enabled"
    istio:
      gateway.knative-serving.knative-ingress-gateway: istio-ingressgateway.istio-ingress.svc.cluster.local
```

Does anyone know how to achieve this?

---

I did try editing the activator deployment manually. It updates fine, but then immediately gets reverted back. I am assuming the operator does this.
