### ISSUE TITLE
Support podAntiAffinity spec

### ISSUE THREAD

**Issue by krithika369** [knative/operator#1331]
**Problem**
Hello! We use Knative Serving and [KServe](https://github.com/kserve/kserve) extensively. Recently, we're starting to move our workloads to nodes backed by preemptible VMs and would like to be able to configure [podAntiAffinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity) as a safety measure, to minimize the impact from preemption.

**[Persona:](https://github.com/knative/serving/blob/d5d489c0babd5c9ae9a37d707c06df92d70711f5/docs/product/personas.md)**
Developer, Operator, Motivated User

**Exit Criteria**
Knative Services can be defined with `podAntiAffinity` deployment specs:
```
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - web-store
            topologyKey: "kubernetes.io/hostname"
```

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?
With https://github.com/knative/operator/pull/747 as reference, perhaps no more than 1 day.

**Additional context (optional)**
I'm happy to contribute to this feature with a PR. Any initial pointers would be appreciated.
