### ISSUE TITLE
Unable to set tls on Istio Gateway

### ISSUE THREAD

**Issue by stdmje** [knative/operator#1428]
**Problem**
When trying to setup tls configuration in the Istio Gateway spec i get an error.

```
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    istio:
      enabled: true
      knative-ingress-gateway:
        selector:
          istio: igw-alb-internal
        servers:
          - hosts:
            - '*'
            port:
              name: https
              number: 443
              protocol: HTTPS
            tls:
              credentialName: star-igw-alb-tls
              mode: SIMPLE
      knative-local-gateway:
        selector:
          istio: igw-alb-internal
```

```
error: error validating "STDIN": error validating data: ValidationError(KnativeServing.spec.ingress.istio.knative-ingress-gateway.servers[0]): unknown field "tls" in dev.knative.operator.v1beta1.KnativeServing.spec.ingress.istio.knative-ingress-gateway.servers; if you choose to ignore these errors, turn validation off with --validate=false
```

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Knative events

**Exit Criteria**
I am able to setup tls spec in the Istio Gateway.
