### ISSUE TITLE
Operator ignores spec.ingress.istio.knative-*-gateway.selector in KnativeServing (v1.10x) spec

### ISSUE THREAD

**Issue by qtheya** [knative/operator#1469]
**Describe the bug**
Operator doesn't patch KnativeServing gateway selector and uses default value
```yaml
spec:
  ingress:
    istio:
      enabled: true
      knative-*-gateway:
        selector: my-custom-selector
```

**Expected behavior**
istio selectors can be set via KnativeServing spec as in previous versions

**To Reproduce**
apply KnativeServing config with custom istio selectors
kubectl get gateway -n knative-serving knative-ingress-gateway -o yaml

**Knative release version**
Operator 1.10.x
Serving 1.10.x

**Additional context**
It works well on previous versions of Serving
