### ISSUE TITLE
Service account token is not added to pods such as kafka controller that are installed with knative eventing source

### ISSUE THREAD

**Issue by kahirokunn** [knative/operator#1474]
**Problem**

All pods that run the k8s api must be set to accountServiceAccountToken: true

```
automountServiceAccountToken: true
```

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by kahirokunn** [comment]
Keep

**Comment by kahirokunn** [comment]
Jeep

**Comment by kahirokunn** [comment]
Keep

**Comment by kahirokunn** [comment]
keep

**Comment by houshengbo** [comment]
@kahirokunn Where do you propse to add `accountServiceAccountToken`?

**Comment by kahirokunn** [comment]
How about this?

```yaml
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  automountServiceAccountToken: true # here
  # ...
  source:
    kafka:
      enabled: true
```
