### ISSUE TITLE
Allow specifying resource limits and requests for Eventing storage-version-migration job

### ISSUE THREAD

**Issue by Desolar1um** [knative/operator#1494]
**Problem**
While resource limits/requests can be defined for deployments, this is not yet possible for Jobs it seems. I am running a cluster where jobs cannot be created without resource limits/requests set.

**Exit Criteria**
The possibility to define resources for jobs, ex:

```
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  deployments:
  - name: eventing-controller
    resources:
    - container: eventing-controller
      requests:
        cpu: ${eventing_controller_cpu_requests}
        memory: ${eventing_controller_mem_requests}
      limits:
        cpu: ${eventing_controller_cpu_limits}
        memory: ${eventing_controller_mem_limits}
       ...
  jobs:
  - name: storage-version-migration-eventing-eventing-1.10.1
    resources:
    - container: migrate
      requests: 
        cpu: xm
        memory: yMi 
      limits:
        cpu: xm
        memory: yMi 
```

**Time Estimate (optional):**
3-5
