### ISSUE TITLE
Publish helm chart with each release

### ISSUE THREAD

**Issue by acelinkio** [knative/operator#1525]
**Describe the bug**
Helm chart is not published into a helm repository.

**Expected behavior**
Have a helm chart available with each release (or a known cadence).

**Additional context**
https://github.com/knative/operator/pull/1447 added a helm chart
https://github.com/knative/operator/pull/1501 modified behavior to generate helm chart

Would greatly appreciate if this chart was published somewhere so this operator could be deployed using gitops tools.

**Comment by acelinkio** [comment]
Not sure how to best contribute here.  Some teams choose to publish the chart with the same versioning as the project, others split it out.

**Comment by houshengbo** [comment]
@acelinkio Are you interested in publishing helm charts? Feel free to contribute. Thx.

**Comment by Qwiko** [comment]
Is this something that is being worked on? I am very interested in deploying the Knative Operator with GitOps methods.

**Comment by kromanow94** [comment]
Hey, my two cents here:
* This is a big pain point that the Helm Chart is not released anywhere.
* It would be possible to use ArgoCD with Helm Chart source as a git repository but the [config/charts/knative-operator/Chart.yaml](https://github.com/knative/operator/blob/4d616234ad3ea4aad42adcb78d82c6005f486543/config/charts/knative-operator/Chart.yaml#L3) uses hacky `{{ version }}` variable that is provided through the `./hack/generate-helm.sh` described [here](https://github.com/knative/operator/blob/main/docs/release.md#release-the-helm-chart) which makes this unusable.

    ```yaml
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: knative-operator
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: knative-operator
      project: default
      sources:
        - repoURL: https://github.com/knative/operator.git
          targetRevision: knative-v1.11.12
          path: config/charts/knative-operator
    ```

    The above ArgoCD App example would basically download the repo and checkout a specific version and execute `helm template`, but the following error is blocking this:
    ```
    Error: cannot load Chart.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"version":interface {}(nil)}
    ```

* There are nice tools that helps in releasing the Helm Chart with GitHub Repository serving as a Helm Chart Repository. One example would be the [Chart Releaser](https://github.com/helm/chart-releaser). But, the Helm Chart Release process in `knative/opreator` is using the `./hack/generate-helm.sh` and hacky `{{ version }}` in the `Chart.yaml`. Without it, it would be fairly straightforward to automate the Helm Chart Release process. Another idea would be to define a custom GH Workflow that would automate this process.

* Another way to have a GitHub Repository as a Helm Chart Repository relates to manual creation of the `index.yaml` file and host it behind GitHub Pages. TL;DR:
  * Create branch (can be empty) for GitHub Pages to point as the source of what to host.
  * Create some simple `index.html` file for GitHub Pages to have something to host on the webpage.
  * Create simple `index.yaml` file that contains information about the Helm Charts and their URL to the archive
    * example: https://helm.sh/docs/topics/chart_repository/#the-index-file
  * Configure GitHub Pages in the GitHub Repository config.

Resources:
* https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site
* https://helm.sh/docs/topics/chart_repository
* https://github.com/helm/chart-releaser

/reopen

/remove-lifecycle stale
