### ISSUE TITLE
Allow static replicas of knative-serving workloads to be created

### ISSUE THREAD

**Issue by husnialhamdani** [knative/operator#1574]
**Problem**
Based on https://knative.dev/docs/install/operator/configuring-serving-cr/#override-replicas-labels-and-annotations, there's no way to define a static replicas, in certain case, specifiying static number would be needed.

**Exit Criteria**
Allow user to have a static number of replicas.

**Comment by houshengbo** [comment]
If you want specify the number of replicas, this is how you can do it 
```spec:
...
  workloads:
  - name: webhook
    replicas: 3
```
The workloads, you can specify the name of the deployment/daemonset/statefulset, etc. In this example, webhook is the name.

**Comment by husnialhamdani** [comment]
Still doesn't works, I tried like this. The HPA still there.

```
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  workloads:
   - name: activator
     replicas: 5
   - name: webhook
     replicas: 3
  podDisruptionBudgets:
    - name: activator-pdb
      minAvailable: 1
    - name: webhook-pdb
      minAvailable: 1
```
