### ISSUE TITLE
Add possibility to assign annotations to Kourier LoadBalancer

### ISSUE THREAD

**Issue by timosur** [knative/operator#1627]
**Problem**
Currently it is not possible to assign annotations to the Kourier LoadBalancer. We currently have a hard requirement to do that as we need to set azure-load-balancer-internal annotation. Otherwise our LoadBalancer will just be rejected by our company Azure Policies.

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Which persona is this feature for?
[System Operator](https://github.com/knative/eventing/blob/main/docs/personas.md#system-operator)

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.
It is possible to assign azure-load-balancer-internal to the Kourier LoadBalancer.

**Comment by norbjd** [comment]
Hello @timosur, we had a similar need (with another annotation), and found a solution by using the `spec.services.annotations` field in `KnativeServing` object:

```
$ kubectl explain knativeserving.spec.services.annotations
GROUP:      operator.knative.dev
KIND:       KnativeServing
VERSION:    v1beta1

FIELD: annotations <map[string]string>

DESCRIPTION:
    Annotations overrides labels for the service
```

To define annotations on kourier service, just use:

```yaml
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    kourier:
      enabled: true
  services:
    - name: kourier
      annotations:
        azure-load-balancer-internal: "the-value-you-want"
```

The `kourier` service will now have the `azure-load-balancer-internal` annotation. Hope that helps.
