### ISSUE TITLE
Add load balancer annotations to kourier service from the operator

### ISSUE THREAD

**Issue by zalsader** [knative/operator#1655]
**Problem**
It would be nice if we could add [annotations to the kourier load balancer service](https://github.com/knative-extensions/net-kourier#loadbalancer-configuration) directly from the operator instead of having to do that manually.

Current approach:
```bash
kubectl patch service/kourier \
    -n knative-serving \
    --type merge -p '{"metadata": {"annotations": {"some-provider-specific": "data" }}}'
```

It would be nice if I could do it like this instead:
```yaml
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  # ...
  ingress:
    kourier:
      enabled: true
      annotations:
        some-provider-specific: "data"
```

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
System operator

**Exit Criteria**
The ability to add annotations through the operator.

**Comment by zalsader** [comment]
This is [already implemented](https://knative.dev/docs/install/operator/configuring-serving-cr/#override-system-services). I had to do this:
```yaml
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  # ...
  ingress:
    kourier:
      enabled: true
  services:
    - name: kourier
      annotations:
        load-balancer.hetzner.cloud/name: "my-load-balancer"
```
