### ISSUE TITLE
Update `net-kourier-controller` container name from `controller` to `kourier-controller`

### ISSUE THREAD

**Issue by lou-lan** [knative/operator#1667]
**Problem**

We want use `spec.registry.override` to replace image. 

The operator uses the container name as the logic for replacement, with both the `net-kourier-controller` and the `knative-releases/knative.dev/serving/cmd/controller` container names being `controller`. This will cause two different applications to be replaced with the same image.

```
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  registry:
    override:
      "kourier-gateway": "docker.reg-name.com/envoyproxy/envoy:v1.25-latest"
      "activator": "reg-name.com/gcr.io/knative-releases/knative.dev/serving/cmd/activator:v1.12.2"
      "autoscaler": "reg-name.com/gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler:v1.12.2"
      "autoscaler-hpa": "reg-name.com/gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler-hpa:v1.12.2"
      "controller": "reg-name.com/gcr.io/knative-releases/knative.dev/serving/cmd/controller:v1.12.2"
      "webhook": "reg-name.com/gcr.io/knative-releases/knative.dev/serving/cmd/webhook:v1.12.2"
  ingress:
    kourier:
      enabled: true
  config:
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"
```

```
kubectl get pods  -n knative-serving  net-kourier-controller-655795785b-lvwxh -o yaml | grep 'name: controller'
    name: controller
    name: controller
```

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):**
0.1 day, I can perform the fix, but I need guidance on the location of the changes.

**Additional context (optional)**
Add any other context about the feature request here.
