### ISSUE TITLE
The installation issue with eventing tls networking

### ISSUE THREAD

**Issue by houshengbo** [knative/operator#1737]
**Describe the bug**
Install KnativeEventing CR with default configuration will lead to 
```
no matches for kind "ClusterIssuer" in version "cert-manager.io/v1"
no matches for kind “Certificate” in version “cert-manager.io/v1”
```
in the log of the operator. You can check with `kubectl logs -f deploy/knative-operator`.

**Expected behavior**
There is no error message in the log of the operator.

**To Reproduce**
Install operator 1.13(any patch version) on a clean kubernetes cluster with
```
kubectl apply -f https://github.com/knative/operator/releases/download/knative-v1.13.2/operator.yaml
``` 
and run 
```
cat <<-EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
 name: knative-eventing
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
EOF
```

If your cluster has cert-manager installed, you would not run into this issue.

**Knative release version**
1.11, 1.12, and 1.13

**Additional context**
