### ISSUE TITLE
Support feature flags through KnativeServing CRD in the Operator

### ISSUE THREAD

**Issue by kromanow94** [knative/operator#1838]
**Problem**
It would be nice if the knative feature flags could be configurable through the `KnativeServing` CRD.

https://knative.dev/docs/serving/configuration/feature-flags/

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
System Operator

**Exit Criteria**
Feature flags can be configured by the Operator for knative serving through the KnativeServing CRD.

**Comment by houshengbo** [comment]
@kromanow94 Do you mean to configure the config-features ConfigMap?
The operator is able to configure any ConfigMap available with knative serving and eventing: https://knative.dev/docs/install/operator/configuring-with-operator/#configuring-knative-by-using-the-operator

**Comment by kromanow94** [comment]
Maybe the `config-features` config map is supported by the operator through code but not in the CRD? I wasn't able to find the `features:` section in the CRDs:
* [config/crd/bases/operator.knative.dev_knativeservings.yaml](https://github.com/knative/operator/blob/4d616234ad3ea4aad42adcb78d82c6005f486543/config/crd/bases/operator.knative.dev_knativeservings.yaml)
* [config/charts/knative-operator/templates/operator.yaml](https://github.com/knative/operator/blob/4d616234ad3ea4aad42adcb78d82c6005f486543/config/charts/knative-operator/templates/operator.yaml)

**Comment by mbrancato** [comment]
The docs are not clear. This is how you configure the `config-features` config map:

```yaml
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    features:
      kubernetes.containerspec-addcapabilities: "enabled"
      kubernetes.podspec-init-containers: "enabled"
      kubernetes.podspec-fieldref: "enabled"
      kubernetes.podspec-affinity: "enabled"
      kubernetes.podspec-nodeselector: "enabled"
      kubernetes.podspec-tolerations: "enabled"
      multi-container: "enabled"
      kubernetes.podspec-securitycontext: "enabled"
```
