### ISSUE TITLE
Webhook `subscriptions.messaging.knative.dev` unable to downgrade

### ISSUE THREAD

**Issue by houshengbo** [knative/operator#191]
0.15.x to 0.16.0 goes fine, but 0.16.0 to 0.15.x fails on eventing.

Error message when downgrading from 0.16.0 to 0.15.x for eventing:
```
{"level":"info","ts":"2020-07-13T16:36:36.614Z","logger":"knative-operator.manifestival","caller":"zapr@v0.1.1/zapr.go:69","msg":"Merging","diff":"{\"metadata\":{\"labels\":{\"eventing.knative.dev/release\":\"v0.15.2\"}},\"spec\":{\"conversion\":{\"strategy\":\"None\",\"webhook\":null},\"validation\":{\"openAPIV3Schema\":{\"properties\":{\"spec\":{\"properties\":{\"channel\":{\"description\":\"Channel that forwards incoming events to the subscription.\",\"properties\":{\"apiVersion\":{\"minLength\":1,\"type\":\"string\"},\"kind\":{\"type\":\"string\"},\"name\":{\"minLength\":1,\"type\":\"string\"}},\"required\":[\"apiVersion\",\"kind\",\"name\"],\"type\":\"object\"},\"delivery\":{\"description\":\"Subscription delivery options. More information: https://knative.dev/docs/eventing/event-delivery.\",\"type\":\"object\",\"x-kubernetes-preserve-unknown-fields\":true},\"reply\":{\"description\":\"the destination that (optionally) receive events.\",\"properties\":{\"ref\":{\"description\":\"a reference to a Kubernetes object from which to retrieve the target URI.\",\"properties\":{\"apiVersion\":{\"minLength\":1,\"type\":\"string\"},\"kind\":{\"minLength\":1,\"type\":\"string\"},\"name\":{\"minLength\":1,\"type\":\"string\"},\"namespace\":{\"minLength\":1,\"type\":\"string\"}},\"required\":[\"apiVersion\",\"kind\",\"name\"],\"type\":\"object\"},\"uri\":{\"description\":\"the target URI or, if ref is provided, a relative URI reference that will be combined with ref to produce a target URI.\",\"minLength\":1,\"type\":\"string\"}},\"type\":\"object\"},\"subscriber\":{\"description\":\"the subscriber that (optionally) processes events.\",\"properties\":{\"ref\":{\"description\":\"a reference to a Kubernetes object from which to retrieve the target URI.\",\"properties\":{\"apiVersion\":{\"minLength\":1,\"type\":\"string\"},\"kind\":{\"minLength\":1,\"type\":\"string\"},\"name\":{\"minLength\":1,\"type\":\"string\"},\"namespace\":{\"minLength\":1,\"type\":\"string\"}},\"required\":[\"apiVersion\",\"kind\",\"name\"],\"type\":\"object\"},\"uri\":{\"description\":\"the target URI or, if ref is provided, a relative URI reference that will be combined with ref to produce a target URI.\",\"minLength\":1,\"type\":\"string\"}},\"type\":\"object\"}},\"required\":[\"channel\"],\"type\":\"object\"},\"status\":{\"type\":\"object\",\"x-kubernetes-preserve-unknown-fields\":true}}}},\"versions\":[{\"name\":\"v1alpha1\",\"served\":true,\"storage\":false},{\"name\":\"v1beta1\",\"served\":true,\"storage\":true}]}}"}
{"level":"info","ts":"2020-07-13T16:36:36.617Z","logger":"knative-operator.manifestival","caller":"zapr@v0.1.1/zapr.go:69","msg":"Updating","name":"/subscriptions.messaging.knative.dev","type":"apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition"}
{"level":"error","ts":"2020-07-13T16:36:36.715Z","logger":"knative-operator.manifestival","caller":"zapr@v0.1.1/zapr.go:128","msg":"Failed to update merged resource, trying overwrite","error":"CustomResourceDefinition.apiextensions.k8s.io \"subscriptions.messaging.knative.dev\" is invalid: [spec.conversion.webhookClientConfig: Forbidden: should not be set when strategy is not set to Webhook, spec.conversion.conversionReviewVersions: Forbidden: should not be set when strategy is not set to Webhook]","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tgithub.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/manifestival/manifestival.Manifest.update\n\tgithub.com/manifestival/manifestival@v0.5.1-0.20200702141132-93669fa9179b/manifestival.go:160\ngithub.com/manifestival/manifestival.Manifest.apply\n\tgithub.com/manifestival/manifestival@v0.5.1-0.20200702141132-93669fa9179b/manifestival.go:150\ngithub.com/manifestival/manifestival.Manifest.Apply\n\tgithub.com/manifestival/manifestival@v0.5.1-0.20200702141132-93669fa9179b/manifestival.go:101\nknative.dev/operator/pkg/reconciler/common.Install\n\tknative.dev/operator/pkg/reconciler/common/install.go:50\nknative.dev/operator/pkg/reconciler/common.Stages.Execute\n\tknative.dev/operator/pkg/reconciler/common/stages.go:36\nknative.dev/operator/pkg/reconciler/knativeeventing.(*Reconciler).ReconcileKind\n\tknative.dev/operator/pkg/reconciler/knativeeventing/knativeeventing.go:103\nknative.dev/operator/pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing.(*reconcilerImpl).Reconcile\n\tknative.dev/operator/pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/reconciler.go:169\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20200625173728-dfb81cf04a7c/controller/controller.go:434\nknative.dev/pkg/controller.(*Impl).RunContext.func2\n\tknative.dev/pkg@v0.0.0-20200625173728-dfb81cf04a7c/controller/controller.go:372"}
{"level":"error","ts":"2020-07-13T16:36:36.816Z","logger":"knative-operator","caller":"knativeeventing/reconciler.go:210","msg":"Returned an error","knative.dev/traceid":"f00dd239-bd3f-4245-9390-9035ac711c82","knative.dev/key":"knative-eventing/knative-eventing","targetMethod":"ReconcileKind","error":"failed to apply non rbac manifest: CustomResourceDefinition.apiextensions.k8s.io \"subscriptions.messaging.knative.dev\" is invalid: [spec.conversion.webhookClientConfig: Forbidden: should not be set when strategy is not set to Webhook, spec.conversion.conversionReviewVersions: Forbidden: should not be set when strategy is not set to Webhook]","stacktrace":"knative.dev/operator/pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing.(*reconcilerImpl).Reconcile\n\tknative.dev/operator/pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/reconciler.go:210\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20200625173728-dfb81cf04a7c/controller/controller.go:434\nknative.dev/pkg/controller.(*Impl).RunContext.func2\n\tknative.dev/pkg@v0.0.0-20200625173728-dfb81cf04a7c/controller/controller.go:372"}
{"level":"error","ts":"2020-07-13T16:36:36.817Z","logger":"knative-operator","caller":"controller/controller.go:449","msg":"Reconcile error","error":"failed to apply non rbac manifest: CustomResourceDefinition.apiextensions.k8s.io \"subscriptions.messaging.knative.dev\" is invalid: [spec.conversion.webhookClientConfig: Forbidden: should not be set when strategy is not set to Webhook, spec.conversion.conversionReviewVersions: Forbidden: should not be set when strategy is not set to Webhook]","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20200625173728-dfb81cf04a7c/controller/controller.go:449\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20200625173728-dfb81cf04a7c/controller/controller.go:435\nknative.dev/pkg/controller.(*Impl).RunContext.func2\n\tknative.dev/pkg@v0.0.0-20200625173728-dfb81cf04a7c/controller/controller.go:372"}
{"level":"info","ts":"2020-07-13T16:36:36.817Z","logger":"knative-operator","caller":"controller/controller.go:436","msg":"Reconcile failed. Time taken: 6.139282429s","knative.dev/traceid":"f00dd239-bd3f-4245-9390-9035ac711c82","knative.dev/key":"knative-eventing/knative-eventing"}
{"level":"info","ts":"2020-07-13T16:36:36.817Z","logger":"knative-operator.event-broadcaster","caller":"record/event.go:281","msg":"Event(v1.ObjectReference{Kind:\"KnativeEventing\", Namespace:\"knative-eventing\", Name:\"knative-eventing\", UID:\"44949a2b-b3f8-44c9-895a-574a703733e1\", APIVersion:\"operator.knative.dev/v1alpha1\", ResourceVersion:\"1741\", FieldPath:\"\"}): type: 'Warning' reason: 'InternalError' failed to apply non rbac manifest: CustomResourceDefinition.apiextensions.k8s.io \"subscriptions.messaging.knative.dev\" is invalid: [spec.conversion.webhookClientConfig: Forbidden: should not be set when strategy is not set to Webhook, spec.conversion.conversionReviewVersions: Forbidden: should not be set when strategy is not set to Webhook]"}
```

0.15.3 CRD:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: subscriptions.messaging.knative.dev
  labels:
    eventing.knative.dev/release: "v0.15.3"
    knative.dev/crd-install: "true"
spec:
  group: messaging.knative.dev
  preserveUnknownFields: false
  names:
    kind: Subscription
    plural: subscriptions
    singular: subscription
    categories:
    - all
    - knative
    - eventing
    shortNames:
    - sub
  scope: Namespaced
  subresources:
    status: {}
  conversion:
    strategy: None
    #    strategy: Webhook
    #    webhookClientConfig:
    #      service:
    #        name: eventing-webhook
    #        namespace: knative-eventing
  additionalPrinterColumns:
  - name: Ready
    type: string
    JSONPath: ".status.conditions[?(@.type==\"Ready\")].status"
  - name: Reason
    type: string
    JSONPath: ".status.conditions[?(@.type==\"Ready\")].reason"
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          required:
          - channel
          type: object
          properties:
            channel:
              type: object
              description: "Channel that forwards incoming events to the subscription."
              required:
              - apiVersion
              - kind
              - name
              properties:
                apiVersion:
                  type: string
                  minLength: 1
                kind:
                  type: string
                name:
                  type: string
                  minLength: 1
            subscriber:
              type: object
              description: "the subscriber that (optionally) processes events."
              properties:
                uri:
                  type: string
                  description: "the target URI or, if ref is provided, a relative
                    URI reference that will be combined with ref to produce a target
                    URI."
                  minLength: 1
                ref:
                  type: object
                  description: "a reference to a Kubernetes object from which to retrieve
                    the target URI."
                  required:
                  - apiVersion
                  - kind
                  - name
                  properties:
                    apiVersion:
                      type: string
                      minLength: 1
                    kind:
                      type: string
                      minLength: 1
                    name:
                      type: string
                      minLength: 1
                    namespace:
                      type: string
                      minLength: 1
            reply:
              type: object
              description: "the destination that (optionally) receive events."
              properties:
                uri:
                  type: string
                  description: "the target URI or, if ref is provided, a relative
                    URI reference that will be combined with ref to produce a target
                    URI."
                  minLength: 1
                ref:
                  type: object
                  description: "a reference to a Kubernetes object from which to retrieve
                    the target URI."
                  required:
                  - apiVersion
                  - kind
                  - name
                  properties:
                    apiVersion:
                      type: string
                      minLength: 1
                    kind:
                      type: string
                      minLength: 1
                    name:
                      type: string
                      minLength: 1
                    namespace:
                      type: string
                      minLength: 1
            delivery:
              description: "Subscription delivery options. More information: https://knative.dev/docs/eventing/event-delivery."
              type: object
              x-kubernetes-preserve-unknown-fields: true
        status:
          type: object
          x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: false
  - name: v1beta1
    served: true
    storage: true
```

0.16.0 CRD:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: subscriptions.messaging.knative.dev
  labels:
    eventing.knative.dev/release: "v0.16.0"
    knative.dev/crd-install: "true"
spec:
  group: messaging.knative.dev
  versions:
  - &version
    name: v1alpha1
    served: false
    storage: false
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        # this is a work around so we don't need to flush out the
        # schema for each version at this time
        #
        # see issue: https://github.com/knative/serving/issues/912
        x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: Ready
      type: string
      jsonPath: ".status.conditions[?(@.type==\"Ready\")].status"
    - name: Reason
      type: string
      jsonPath: ".status.conditions[?(@.type==\"Ready\")].reason"
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  - !!merge <<: *version
    name: v1beta1
    served: true
    storage: true
  - !!merge <<: *version
    name: v1
    served: true
    storage: false
  names:
    kind: Subscription
    plural: subscriptions
    singular: subscription
    categories:
    - all
    - knative
    - eventing
    shortNames:
    - sub
  scope: Namespaced
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions: ["v1", "v1beta1"]
      clientConfig:
        service:
          name: eventing-webhook
          namespace: knative-eventing

```

**Comment by houshengbo** [comment]
@jcrossley3 Have you seen this error?
FYI @vaikas

**Comment by jcrossley3** [comment]
> @jcrossley3 Have you seen this error?

No. And I don't fully understand how the v1 and v1beta1 CRD schemas are supposed to reconcile.

**Comment by houshengbo** [comment]
```
kubectl patch crd subscriptions.messaging.knative.dev --type='json' -p '[{"op" : "remove", "path" : "/spec/conversion/webhook"},{"op":"replace", "path":"/spec/conversion/strategy","value" : "None"}]
```
As @vaikas said, we need to run the above command.
How can we add it into knative operator 0.15 branch?

**Comment by houshengbo** [comment]
As we do three-way merging with manifestival, v1beta1 -> v1 is fine. But v1->v1beta1, crd is still v1.

**Comment by vaikas** [comment]
Perhaps we could release a .15.4 that has the subscription CRD definition changed like this:
Current:
```
    strategy: None
    #    strategy: Webhook
    #    webhookClientConfig:
    #      service:
    #        name: eventing-webhook
    #        namespace: knative-eventing
```

Change it to this:
```
    strategy: Webhook
    webhookClientConfig:
      service:
       name: eventing-webhook
        namespace: knative-eventing
```
Do you have a way to try out with that change to see if the downgrade goes clean? If it does, we could cut a release with that.
