### ISSUE TITLE
Helm: Knative Operator isn't removing finalizers when uninstalling

### ISSUE THREAD

**Issue by Evynglais** [knative/operator#1950]
**Describe the bug**
Uninstalling the helm chart does not remove finalizers that were added to the knative-serving and knative-eventing resources, which means they can't be deleted.

**Expected behavior**
Uninstalling the Knative helm chart should remove any finalizers to allow other resources to be removed gracefully.

**To Reproduce**
Install the operator using the Knative Helm chart. Apply the following YAML files (requires the namespaces to exist):

```yaml
  apiVersion: operator.knative.dev/v1beta1
  kind: KnativeEventing
  metadata:
      name: knative-eventing
      namespace: knative-eventing
```

```yaml
  apiVersion: operator.knative.dev/v1beta1
  kind: KnativeServing
  metadata:
      name: knative-serving
      namespace: knative-serving
  spec:
      ingress:
          kourier:
              enabled: true
```

Uninstall the helm chart, and inspect the above resources. The will both have finalizers that block them from being deleted.

**Knative release version**
v1.16.0

**Additional context**
Testing environment: KIND, Docker Desktop, Windows 11. Also tested on an RKE2 cluster in Google Cloud.

Low priority. Finalizers can be removed by editing the resources and setting them to empty which allows the resource to be removed. See [2668](https://github.com/knative/eventing/issues/2668) for a similar issue.
