### ISSUE TITLE
Serving and Eventing can't be deployed in the same namespace

### ISSUE THREAD

**Issue by eloo-abi** [knative/operator#2014]
**Describe the bug**
Hi, 
i have just discovered that it is not possible to have knative serving and eventing in the same namespace due to resource name clashes.

It looks like the both components try to use the same naming for their config maps (at least what i have seen).
So these config maps gets overwritten by the other component the whole time.

**Expected behavior**
I would expect both component have their own config maps.
e.g. `config-eventing-features` and `config-serving-features` or better with the name of the component resource

**To Reproduce**
Deploy serving and eventing using the helm chart of the operator in the same namespace.

```
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-system
spec:
  config:
    features:
      cross-namespace-event-links: "enabled"

--- 
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
spec:
  config:
    features:
      queueproxy.resource-defaults: "disabled" 
```

Them deploy it and check the configmap `config-features`.
You will see that the content will change everytime you do a change in one of the both CRD configs in features.

**Knative release version**
1.17.3

**Additional context**
