### ISSUE TITLE
knative-operator 1.17.3 can't deploy knative-serving 1.15.3

### ISSUE THREAD

**Issue by bacek** [knative/operator#2032]
**Describe the bug**
knative-operator 1.17.3 can't deploy knative-serving 1.15.3

**Expected behavior**
knative-operator deploys serving 1.15.3

**To Reproduce**
According to https://knative.dev/docs/install/operator/knative-with-operators/, operator 1.17 should be able to deploy serving 1.15.2

Creating CR:
```
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: dev-knative-serving-0ea1a91f
  namespace: knative-serving
spec:
  config:
    features:
      kubernetes.podspec-affinity: enabled
      kubernetes.podspec-persistent-volume-claim: enabled
      kubernetes.podspec-persistent-volume-write: enabled
      kubernetes.podspec-tolerations: enabled
    gc:
      max-non-active-revisions: "0"
      min-non-active-revisions: "0"
      retain-since-create-time: disabled
      retain-since-last-active-time: disabled
    network:
      domain-template: '{{.Name}}.{{.Domain}}'
      ingress-class: kourier.ingress.networking.knative.dev
  ingress:
    kourier:
      enabled: true
  version: v1.15.3
 
```

results in this `status`:
```
status:
  conditions:
  - lastTransitionTime: "2025-03-18T05:29:13Z"
    status: Unknown
    type: DependenciesInstalled
  - lastTransitionTime: "2025-03-18T05:29:13Z"
    status: Unknown
    type: DeploymentsAvailable
  - lastTransitionTime: "2025-03-18T05:29:13Z"
    message: 'Install failed with message: the manifests of the target version v1.15.3
      are not available to this release'
    reason: Error
    status: "False"
    type: InstallSucceeded
  - lastTransitionTime: "2025-03-18T05:29:13Z"
    message: 'Install failed with message: the manifests of the target version v1.15.3
      are not available to this release'
    reason: Error
    status: "False"
    type: Ready
  - lastTransitionTime: "2025-03-18T05:29:13Z"
    status: "True"
    type: VersionMigrationEligible

```

**Knative release version**
operator: v1.17.3
serving: v1.15.2

**Additional context**
No deployments in `knative-serving` namespace created.
