### ISSUE TITLE
How to update resources for net-kourier-controller

### ISSUE THREAD

**Issue by exilehanharr** [knative/operator#2076]
Hello everyone!

I've tried to deploy knative using operator and have got issue with `net-kourier-controller`. The controller is killed by OOM.

I've tried to increase limits but it doesn't work.

Example:

```yaml
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
spec:
  ingress:
    kourier:
      enabled: true
  config:
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"
  deployments:
    - name: net-kourier-controller
      resources:
        - container: net-kourier-controller
          requests:
            cpu: 200m
            memory: 250Mi
          limits:
            cpu: 500m
            memory: 2Gi
```

I use operator version `1.11.12` because my k8s cluster version compatibillity.

How I can increase limits for `net-kourier-controller`?

**Comment by exilehanharr** [comment]
I've also tried using workloads, but it didn't work.

I couldn't find any documentation on how to use the operator. Can anyone help me with my question?

**Comment by houshengbo** [comment]
The name under `workloads` or `deployments` should be the name of the deployment resource.
Then the container name should be the name of the container. By looking at the manifest of kourier.yaml, the deployment name is `net-kourier-controller` and the container name is `controller`. Try the following:

```
...
spec:
  workloads:
  - name: net-kourier-controller
    resources:
    - container: controller
      requests:
        cpu: 200m
        memory: 250Mi
      limits:
        cpu: 500m
        memory: 2Gi
...
```
