### ISSUE TITLE
Configuring Kafka as the default broker class

### ISSUE THREAD

**Issue by wuminorb** [knative/operator#2105]
**Problem**
According to the [doc](https://knative.dev/docs/install/operator/configuring-eventing-cr/#configuring-the-default-broker-class), only ChannelBasedBroker and MTChannelBasedBroker are supported. Is there a way to set Kafka as the default broker class?

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
System operator

**Exit Criteria**
```
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  defaultBrokerClass: Kafka
  ...
```

**Time Estimate (optional):**
Not sure

**Additional context (optional)**
As ChannelBasedBroker and MTChannelBasedBroker are not recommended for production. We want to have this to support the production deployment.
