### ISSUE TITLE
Adding `spec.manifests` support to specify customized yamls

### ISSUE THREAD

**Issue by houshengbo** [knative/operator#227]
This is one feature documented in https://docs.google.com/document/d/1ehd5Yx4aSottuv7FYW4JeplNULJCs7nnDfy29y3NH8k/:

Operator CRs have supported `spec.version`. Next, we will offer admins the flexibility to specify links of customized yamls.

```
spec:
  version: 0.14.0
  manifests:
  - URL: https://github.com/knative/serving/releases/${version}/serving-core.yaml
  - URL: https://github.com/knative/serving/releases/${version}/serving-cert-manager.yaml
  - URL: https://github.com/knative/net-istio/releases/${version}/net-istio.yaml
```

Admins can specify the the manifests by the full URL links, or links with ${version} parameter to be replaced by the spec.version.
For example, if one URL is `https://github.com/knative/serving/releases/download/v${version}/serving-core.yaml`, operator will translate the link into `https://github.com/knative/serving/releases/download/v0.14.0/serving-core.yaml`.

With spec.manifests, admins can install any official release of knative, available online, but not available inside the operator, or any customized manifests available online.

**Comment by jcrossley3** [comment]
Any particular reason for `sourceUrl`? Can it just be `url`? Or even just a string unless there are other fields for each manifest, in which case, can they be listed here, too?

**Comment by houshengbo** [comment]
I just copied and pasted the contents in the design doc.
'sourceUrl' can be replaced with "URL".

**Comment by houshengbo** [comment]
**For new official releases:**
If there is a new knative serving release, e.g. 0.17.0, we can install this version, with the current operator without bundling. The serving CR is written like:
```
spec:
  version: 0.17.0
  manifests:
  - URL: https://github.com/knative/serving/releases/v${version}/serving-core.yaml
  - URL: https://github.com/knative/serving/releases/v${version}/serving-hpa.yaml
  - URL: https://github.com/knative/serving/releases/v${version}/serving-post-install-jobs.yaml
```

**For customized releases:**
Manifests can be published anywhere, e.g. `https://my-knative/serving/releases/v0.17.0/serving-core.yaml`.
Define serving CR as:
```
spec:
  version: 0.17.0
  manifests:
  - URL: https://my-knative/serving/releases/v${version}/serving-core.yaml
```
