### ISSUE TITLE
Provide better configuration options for Knative Eventing

### ISSUE THREAD

**Issue by matzew** [knative/operator#231]
**Problem**
Some options are not easily to configure, using the operator. Some have a direct field on the `spec`, like for `defaultBroker`, and some are a bit more "complex" to configure, via embedding ConfigMap cfg into the spec, like described here: https://knative.dev/development/install/operator/configuring-eventing-cr/#eventing-configuration-by-configmap

**Missing options**

It is currently NOT possible to configure the `SINK_BINDING_SELECTION_MODE` evn-var, from the `eventing webhook` deployment. Overriding the value does not work, when using the operator (at least until 0.16)

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Operators

**Comment by matzew** [comment]
> It is currently NOT possible to configure the SINK_BINDING_SELECTION_MODE evn-var, from the eventing webhook deployment. Overriding the value does not work, when using the operator (at least until 0.16)

True with current MASTER as well

**Comment by matzew** [comment]
@houshengbo  ping

**Comment by aliok** [comment]
@markusthoemmes @houshengbo @Cynocracy @jcrossley3 

Unless anybody has a better idea, I would like to add a new field in the CR to override the env vars in the manifests.
Similar to image overrides.

For example:

```
spec:
  environment:
    override:
      SINK_BINDING_SELECTION_MODE: "inclusion"
```

This would look for all env vars in all PodSpecables' containers and override as necessary.

Not sure if we want to go more specific, supporting the PodSpecable name, container name, etc like:
```
spec:
  environment:
    override:
      # 1. update env var in all PodSpecables (deployments, etc.)
      SINK_BINDING_SELECTION_MODE: "inclusion"
      # 2. update env var only for containers within 'eventing-webhook' deployment
      eventing-webhook/SINK_BINDING_SELECTION_MODE: "inclusion"
      # 3. update env var only 'eventing-webhook' container within 'eventing-webhook' deployment
      eventing-webhook/eventing-webhook/SINK_BINDING_SELECTION_MODE: "inclusion"
```
