### ISSUE TITLE
ConfigMap gets overwritten

### ISSUE THREAD

**Issue by lephyrius** [knative/operator#264]
**Describe the bug**
I have a Kubernetes cluster with istio and Knative installed with Knative Operator. 
`kubectl apply --filename https://github.com/knative/operator/releases/latest/download/operator.yaml`
After I installed everything I apply this config map:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
  mydomain.com: ""
```

But after a couple of hours it resets to the default map again with the `example.com` domain.

**Expected behavior**
I expect my domain name default config to stay there forever. 

**To Reproduce**
1. Install latest knative with the operator.
2. Apply a domain name config.
3. Wait a few hours or try to deploy something using `kubectl apply`.
4. The config has been reset to `example.com` configuration.

**Knative release version**
0.17.1

**Additional context**
I use Digital Oceans managed kubernetes.

**Comment by lephyrius** [comment]
I think I found the answer here:
https://knative.dev/development/install/operator/configuring-serving-cr/#serving-configuration-by-configmap

So I need to use the operators own api?
```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    domain:
      mydomain.com: ""
```

Please confirm if this is the case.
