### ISSUE TITLE
Add the support to install event sources

### ISSUE THREAD

**Issue by houshengbo** [knative/operator#298]
**Problem**
We cannot install any event resource available in https://github.com/knative/eventing-contrib.
Install the event sources available in the repo eventing-contrib. Make the CR able to configure the list of event sources, to be installed in the knative eventing.
The custom resource will look like this:
```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  event-contrib:
    version: 0.12.1
    sources: github,kafka
```

We can use a comma separated string to specify all the event sources to be installed. Or use the following CR
```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  event-contrib:
    version: 0.12.1
    sources:
      - github
      - kafka
```

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Which persona is this feature for?
Administrators.

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by houshengbo** [comment]
We used to have a discussion on this feature: https://github.com/knative/eventing-operator/issues/92

**Comment by matzew** [comment]
How does that relate to:   https://github.com/knative/operator/issues/206  ??

**Comment by houshengbo** [comment]
We can leverage the same model in knative serving CR, defining the ingress, to install an eventing source:
```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  version: "0.22"
  eventingSource:
    github:
      enabled: true
      multiTenant: true
```

The field `multiTenant: true` is used to determine it is single or multi tenant. This field is available for github and kafkasource.
