### ISSUE TITLE
Security: Please set pod Security Context on all Pods

### ISSUE THREAD

**Issue by AceHack** [knative/operator#3]
Many companies have a security requirement in place that all pods must not run as root and set the run as user.  Please set this (Or allow it to be set) on all pods.  This would mean either adding it yourself or adding it to any CRDs that end up creating pods so the user can set it.  Note this is at the pod level, not the container level.  I will be creating a separate feature request for the container security content.

https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

See the pod security context example below for what is required to be set.
```
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
```

Related Feature Request: https://github.com/knative/eventing/issues/2881
