### ISSUE TITLE
Error no such file or directory when Using Operator

### ISSUE THREAD

**Issue by zhaojizhuang** [knative/operator#361]
**Problem**
when I install Knative Serving using Operator
if fails,logs as follows:
```shell
{"level":"error","ts":"2020-11-20T22:18:13.254Z","logger":"knative-operator.knative.dev-operator-pkg-reconciler-knativeserving.Reconciler","caller":"controller/controller.go:528","msg":"Reconcile error","knative.dev/pod":"knative-operator-cf9947f8b-vgn8v","error":"stat : no such file or directory","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20201026165741-2f75016c1368/controller/controller.go:528\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20201026165741-2f75016c1368/controller/controller.go:514\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20201026165741-2f75016c1368/controller/controller.go:451"}
{"level":"info","ts":"2020-11-20T22:18:13.254Z","logger":"knative-operator.knative.dev-operator-pkg-reconciler-knativeserving.Reconciler","caller":"controller/controller.go:515","msg":"Reconcile failed. Time taken: 400.578µs","knative.dev/pod":"knative-operator-cf9947f8b-vgn8v","knative.dev/traceid":"fabf4b5b-5d6b-48ce-b8b4-54e2047f1a2e","knative.dev/key":"knative-serving/knative-serving"}
{"level":"info","ts":"2020-11-20T22:18:13.254Z","logger":"knative-operator.event-broadcaster","caller":"record/event.go:278","msg":"Event(v1.ObjectReference{Kind:\"KnativeServing\", Namespace:\"knative-serving\", Name:\"knative-serving\", UID:\"f06dc593-cecd-41a3-8a46-2927cb86598f\", APIVersion:\"operator.knative.dev/v1alpha1\", ResourceVersion:\"3304210\", FieldPath:\"\"}): type: 'Warning' reason: 'InternalError' stat : no such file or directory","knative.dev/pod":"knative-operator-cf9947f8b-vgn8v"}
```
Error: `Warning' reason: 'InternalError' stat : no such file or directory"`

Operator CR is :

```yaml
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: 0.18.0
```
**Expected behavior**
install knative-serving successfully

**To Reproduce**

**Knative release version**
The Knative operator 0.18.0
kubernetes 1.19.4

**Additional context**
Add any other context about the problem here such as proposed priority

**Comment by zhaojizhuang** [comment]
It succeed when i use operator 0.19.0

**Comment by houshengbo** [comment]
@zhaojizhuang Are you using
```
kubectl apply -f https://github.com/knative/operator/releases/download/v0.15.0/operator.yaml
```
to install 0.18.0 operator? What is your existing environment?

I just tried. Knative serving can install fine with the creation of

```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: 0.18.0
```
