### ISSUE TITLE
activator's PDB creates with no disruptionsAllowed when there are a few replicas

### ISSUE THREAD

**Issue by nak3** [knative/operator#376]
Since https://github.com/knative/serving/commit/591510c0c917d4b45ea919568181a75426b543e0 was introduced, activator's PDB has `80%` and operator includes [the PDB](https://github.com/knative/operator/blob/release-0.18/cmd/operator/kodata/knative-serving/0.18.2/2-serving-core.yaml#L2101-L2112) without any change.
PDB 80% creates with zero `disruptionsAllowed` even if we have 2 or some replicas, so it will block an eviction.

e.g. Even 2 activator replicas, `disruptionsAllowed` is zero.

```
spec:
  minAvailable: 80%
  selector:
    matchLabels:
      app: activator
status:
  currentHealthy: 2
  desiredHealthy: 2
  disruptionsAllowed: 0
  expectedPods: 2
  observedGeneration: 1
```

The users who installed Knaative by operator cannot modify the PDB so operator should manage the PDB well or document this HA restriction.
