### ISSUE TITLE
Resource settings do not propagate

### ISSUE THREAD

**Issue by antoineco** [knative/operator#382]
**Describe the bug**

Resources requirements defined as described at https://knative.dev/docs/install/operator/configuring-eventing-cr/#system-resource-settings do not propagate to the target deployment(s).

Tested in an already existing installation, didn't test in a new installation.

**Expected behavior**

Resources requirements do propagate.

**To Reproduce**

```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventingf
spec:
  version: 0.19.2
  resources:
  - container: imc-dispatcher
    requests:
      cpu: 200m
      memory: 250Mi
    limits:
      cpu: "3"
      memory: 1200Mi
```

**Knative release version**

`v0.19.1`

**Additional context**
