### ISSUE TITLE
Allow defining Pod Annotations from the KnativeServing Custom Resource 

### ISSUE THREAD

**Issue by rawc0der** [knative/operator#442]
**Problem**
I have encountered a lot of use-cases where custom annotations need to be provided for the deployed resources. 
For my most recent context, the `KnativeServing` crd is lacking configuration options for injecting annotations into the `Activator pods` and making my life hard.

Example desired usage of custom annotation fields:
```
    apiVersion: operator.knative.dev/v1alpha1
    kind: KnativeServing
    metadata:
      name: knative-serving
      namespace: knative-serving
    spec:
      version: 0.XX.0
      config:
        defaults:
...   
       activator:
         podAnnotations: 
           custom/annotations: "values"
```

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Which persona is this feature for?
- Event Consumers / Developers using or setting up Knative

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.
- Allow templating from helm and verify annotations are inserted. 

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?
 - 1

**Additional context (optional)**
Add any other context about the feature request here.
- If anyone thinks it would be an easy task for an outsider and has a few pointers, I am keen on contributing but am not sure where this fits right now. must catch up on reading the code base.
- I am sure this is not the only use case requiring users setting pod annotations, thus I propose to allow annotations on all the resources the CRD's are managing.

Thanks
