### ISSUE TITLE
Enabled Kourier ingress only works under the namespace `knative-serving`

### ISSUE THREAD

**Issue by houshengbo** [knative/operator#454]
**Describe the bug**
The kourier ingress needs to be installed under the ns `knative-serving` in order to work.

**Expected behavior**
The kourier ingress should work under any namespace.

**To Reproduce**
Apply the serving CR like this:
```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    network:
      ingress.class: "kourier.ingress.networking.knative.dev"
  ingress:
    kourier:
      enabled: true
```

If the namespace is something else other than `knative-serving`, the ingress does not function well.

**Knative release version**
Master

**Comment by houshengbo** [comment]
@nak3 We can leverage the following serving CR to overwrite the ns:

```
apiVersion: v1
kind: Namespace
metadata:
 name: knative-serving
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving-new
spec:
  config:
    network:
      ingress.class: "kourier.ingress.networking.knative.dev"
    kourier-bootstrap:
      envoy-bootstrap.yaml: |
        static_resources:
        - name: xds_cluster
          load_assignment:
            endpoints:
              lb_endpoints:
                endpoint:
                  address:
                    socket_address:
                      address: "kourier-control.knative-serving-new"
  ingress:
    kourier:
      enabled: true
```
