### ISSUE TITLE
 Job storage-version-migration-serving-serving-0.21.0 unable to use private registry image

### ISSUE THREAD

**Issue by yang59324** [knative/operator#520]
**Describe the bug**
when i start the knative-serving of cr, Job storage-version-migration-serving-serving-0.21.0 pull image gcr.io/knative-releases/knative.dev/serving/vendor/knative.dev/pkg/apiextensions/storageversion/cmd/migrate@sha256:4e44b147321c96767328f6c6551964c93c9805ae14ff9f99a01c01a02c056a38 ,but I want to use private registry image,Where can I configure it?

**Knative release version**
The Knative version is 0.21.0

**Comment by MartinForReal** [comment]
please refer to https://knative.dev/docs/install/operator/configuring-serving-cr/#private-repository-and-private-secrets

For  storage-version-migration

the image key is migrate e.g. migrate: xxxxx/knative/job:xxxxx

**Comment by houshengbo** [comment]
It should be like the following CR to configure. If it does not work, log the issue plz:
```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  registry:
    override:
      ...
      migrate: xxxxx/knative/job:xxxxx
      ...
```

Use `migrate`, the container name.
