### ISSUE TITLE
Knative operator looks for "istio-system" namespace when custom istio gateway is set

### ISSUE THREAD

**Issue by jakoberpf** [knative/operator#565]
**Describe the bug**
When we deploy the knative operator and set the custom `knative-ingress-gateway` to another gateway and namespace, the knative serving controller still looks for the `istio-system` namespace and fails to get ready.

operator log: `failed to apply non rbac manifest: namespaces \"istio-system\" not found`

describe of KnativeServing: `Install failed with message: namespaces "istio-system" not found`

**Expected behavior**
When setting the custom gateway, knative doesn't look for the gateway in `istio-system`, but the defined namespace for example `servicemesh`.

**To Reproduce**
Deploy istio in custom namespace and knative with the following configs.

**Knative release version**
Knative Operator: v0.21.0 - v0.22.0

**Additional context**
Serving Configuration:

```---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: platform-knative-serving
spec:
  version: 0.22.0
  config:
    domain:
    istio:
      gateway.knative-serving.knative-ingress-gateway: "app-gateway.servicemesh.svc.cluster.local"
  ingress:
    istio:
      enabled: true
      knative-ingress-gateway:
        selector:
          istio: custom-gateway
```

If we have an obviously misconfiguration please point me out...

**Comment by nak3** [comment]
I think it is bug in https://github.com/knative/operator/blob/main/pkg/reconciler/knativeserving/common/ingress_service.go#L28.
Perhaps creating a `istio-system` namespace could be a workaround? (operator will deploy `knative-local-gateway` svc though.)

**Comment by jakoberpf** [comment]
@nak3 Creating the istio-system namespace created removed the error and created the `knative-local-gateway` as you predicted. The code snipped tells me that the `istio-system` namespace is hard coded and therefore can be changed?

Furthermore when I read the [documentation](https://github.com/knative/operator/blob/main/docs/configuration.md#speccluster-local-gateway) right, we can not set the operator to create this svc in another namespace but would have to create our own local gateway first and then give it the operator?

**Comment by houshengbo** [comment]
@nak3 @jakoberpf 
The line https://github.com/knative/operator/blob/main/pkg/reconciler/knativeserving/common/ingress_service.go#L28 may NOT be the reason leading to the issue, because this line only makes sure the `Service` named `knative-local-gateway` is installed under the default ns istio-system.

**Comment by jakoberpf** [comment]
@houshengbo 
Right, but it means that there must be the default istio-system ns in the cluster for the operator work? So the operator is not build to be used with a **non** default istio-system ns?

**Comment by houshengbo** [comment]
@jakoberpf It should work with non-default ns of istio. We really need to fix this issue.
I suspect it is caused by this resource in net-istio:
```
apiVersion: v1
kind: Service
metadata:
  name: knative-local-gateway
  namespace: istio-system
  labels:
    serving.knative.dev/release: "v0.22.1"
    networking.knative.dev/ingress-provider: istio
spec:
  type: ClusterIP
  selector:
    istio: ingressgateway
  ports:
    - name: http2
      port: 80
      targetPort: 8081
```

**Comment by jakoberpf** [comment]
@houshengbo I actually was looking for a field on the serving cr to point the operator to the namespace where we istio is running. So the idea to add this seems natural to me.

**Comment by houshengbo** [comment]
@jakoberpf 
A few things to confirm: 
- If you only install istio, there is no Service resource called `knative-local-gateway` installed. Correct?
- If you manually install operator from the source code, change the line  https://github.com/knative/operator/blob/main/pkg/reconciler/knativeserving/common/ingress_service.go#L28 into the namespace, where istio is installed, would that work without error?

Could you help me verify these? Thx.

**Comment by jakoberpf** [comment]
@houshengbo 
- correct we do not have a `knative-local-gateway` within our normal istio install. `knative-local-gateway` is only created when the operator is deployed and istio-system ns is created/present. Then `service/knative-local-gateway` also the **only** ressource created in the istio-system ns.
- Yes I should be able to test this tomorrow (along [this](https://github.com/knative/operator/blob/main/docs/development.md) doc) ...

**Comment by houshengbo** [comment]
@jakoberpf 
There is another way to do this so far. If you install the istio under a namspace, for example, `istio-test`, you need to change the configmap `config-istio`. Suppose you install knative serving under ns `knative-serving`. To change it with the operator, you can use the serving CR like:
```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    istio:
      gateway.knative-serving.knative-ingress-gateway: "istio-ingressgateway.istio-test.svc.cluster.local"
      local-gateway.knative-serving.knative-local-gateway: "knative-local-gateway.istio-test.svc.cluster.local"
```

Without changing the schema of the serving CR, operator is able to look up the istio ns by checking `knative-local-gateway.istio-test.svc.cluster.local`. Then set the service `knative-local-gateway` with the correct ns.
