### ISSUE TITLE
No manifest is applied if all Ingresses are disabled

### ISSUE THREAD

**Issue by markusthoemmes** [knative/operator#568]
**Describe the bug**
If an Ingress config is defined, but all Ingress options are disabled, nothing gets installed at all.

**Expected behavior**
Knative gets installed but without any ingress.

**To Reproduce**
Apply the following YAML

```yaml
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    istio:
      enabled: false
    kourier:
      enabled: false
    contour:
      enabled: false
```

Note how nothing gets installed.

**Knative release version**

v0.21 and v0.22

**Additional context**

This is a bug in our defaulting and usage of `mf.Any` here: https://github.com/knative/operator/blob/39d7e473b24ae08101d440b43145d2d135a71fae/pkg/reconciler/knativeserving/ingress/ingress.go#L43-L59. The fix should be fairly straightforward.

/assign
