### ISSUE TITLE
PingSource MT Adapter HA problems

### ISSUE THREAD

**Issue by matzew** [knative/operator#569]
**Describe the bug**

Specifiying HA, on the `KnativeEventing` CR, like:

```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  high-availability:
    replicas: 2
```

I get deployments of `2` for all, expect for the `pingsource-mt-adapter`, which is fine since there is no `PingSource` yet.

See:

```
k get deployments -nknative-eventing
NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
eventing-controller     2/2     2            2           2m
eventing-webhook        2/2     2            2           119s
imc-controller          2/2     2            2           114s
imc-dispatcher          2/2     2            2           114s
mt-broker-controller    2/2     2            2           113s
mt-broker-filter        2/2     2            2           114s
mt-broker-ingress       2/2     2            2           113s
pingsource-mt-adapter   0/0     0            0           2m
sugar-controller        2/2     2            2           112s
```

Now... when I create a `PingSource`, I see _two_ pods created, and one is terminating, since the deployment is "stuck" at `1`:

```
k get deployments -nknative-eventing
NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
eventing-controller     2/2     2            2           17m
eventing-webhook        2/2     2            2           17m
imc-controller          2/2     2            2           17m
imc-dispatcher          2/2     2            2           17m
mt-broker-controller    2/2     2            2           17m
mt-broker-filter        2/2     2            2           17m
mt-broker-ingress       2/2     2            2           17m
pingsource-mt-adapter   1/1     1            1           17m
sugar-controller        2/2     2            2           17m
```

**Expected behavior**

Since I control the HA via the operator, I'd have expected it's also `2` there... instead of staying with `1`.

**To Reproduce**
* set HA
* create a PingSource

**Knative release version**
0.22 (was tested with that)

**Comment by matzew** [comment]
/cc @lionelvillard 
/cc @houshengbo 
/cc @aavarghese 

Any ideas?

**Comment by lionelvillard** [comment]
> I get deployments of 2 for all, expect for the pingsource-mt-adapter, which is fine since there is no PingSource yet.

Is this normal since the operator should set the # of replicas to 2? @houshengbo how does this work?

**Comment by markusthoemmes** [comment]
The deployments supporting HA are enumerated in the respective transformer definition today, see https://github.com/knative/operator/blob/5706b4df85d9b95617d491e4407754cb604bdde9/pkg/reconciler/common/ha.go#L35-L56.

However: Isn't the PingSource stuff prone to the deployment replica fighting thingy, where a different controller than the operator sets the replica count of the PingSource deployment? If so, I'd think **that** component must be configured to put a `2` in there via the setting in the operator (i.e. by adding an env var to that component)

**Comment by houshengbo** [comment]
Eventing release this resource like:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingsource-mt-adapter
  namespace: knative-eventing
  labels:
    eventing.knative.dev/release: "v0.22.1"
spec:
  # when set to 0 (and only 0) will be set to 1 when the first PingSource is created.
  replicas: 0
 ...
```

The number of replicas is 0. Each time the control loop kicks off, the deploy `pingsource-mt-adapter` is reset to 0.
