### ISSUE TITLE
ailed to apply non rbac manifest: no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"

### ISSUE THREAD

**Issue by JCzz** [knative/operator#597]
```
uname -a                                                                                                                                                                                                            
Darwin <username>-MacBook-Pro.local 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64
```

```
kind create cluster --name knative --config clusterconfig.yaml :
```
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      ## expose port 31380 of the node to port 80 on the host
      - containerPort: 31080
        hostPort: 80
      ## expose port 31443 of the node to port 443 on the host
      - containerPort: 31443
        hostPort: 443
```


```
 kubectl get KnativeServing knative-serving -n knative-serving
NAME              VERSION   READY   REASON
knative-serving             False   Error
```

```

kubectl describe KnativeServing knative-serving -n knative-serving
Name:         knative-serving
Namespace:    knative-serving
Labels:       <none>
Annotations:  <none>
API Version:  operator.knative.dev/v1alpha1
Kind:         KnativeServing
Metadata:
  Creation Timestamp:  2021-05-18T19:25:41Z

...
 Warning  InternalError    8s (x13 over 101s)  knativeserving-controller  failed to apply non rbac manifest: no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"

```
