### ISSUE TITLE
Ability to override net-kourier-controller image

### ISSUE THREAD

**Issue by mikluko** [knative/operator#736]
**Problem**
[According to the documentation](https://knative.dev/docs/admin/install/operator/configuring-serving-cr/#private-repository-and-private-secrets), KnativeServing CRD provides means to override various components images. The list of these components doesn't contain `net-kourier` making the image for Kourier hard-coded into the operator.

**Exit Criteria**
```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  registry:
    override:
      net-kourier-controller: docker.io/example/net-kourier/knative.dev/net-kourier/cmd/kourier:latest
```

Above manifest results in `deployment/net-kourier-controller` deployed with the custom image.

**Comment by mikluko** [comment]
After reading sources I managed to get it working. 

```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  registry:
    override:
      net-kourier-controller/controller: docker.io/example/net-kourier/knative.dev/net-kourier/cmd/kourier:latest
```

Note `/controller` suffix on override key.
