### ISSUE TITLE
No error message in `status` if the `spec.version` is not supported

### ISSUE THREAD

**Issue by charles-woshicai** [knative/operator#741]
**Describe the bug**
Operator version: v0.25.0
KnativeServing's `spec.version`: v0.21.0
There is error logs in operator controller, but error is not shown in CR's status.

**Expected behavior**
Show error log in CR's status.

**To Reproduce**
1. install knative-operator with version v0.25.0
2. apply KnativeServing with spec.version=0.21.0 and spec.manifests must not be nil
3. kubectl logs controller-pod-xxx...

**Knative release version**
v0.25.0

**Additional context**

**Comment by houshengbo** [comment]
@charles-woshicai Thanks for reporting this issue. PR is welcome.

**Comment by charles-woshicai** [comment]
Additional information:

Here is my KnativeServing yaml:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  version: 0.21.0
  high-availability:
    replicas: 3
  config:
    observability:
      logging.enable-request-log: "true"
      logging.request-log-template: '{"httpRequest": {"requestMethod": "{{.Request.Method}}", "requestUrl": "{{js .Request.RequestURI}}", "requestSize": "{{.Request.ContentLength}}", "status": {{.Response.Code}}, "responseSize": "{{.Response.Size}}", "userAgent": "{{js .Request.UserAgent}}", "remoteIp": "{{js .Request.RemoteAddr}}", "serverIp": "{{.Revision.PodIP}}", "referer": "{{js .Request.Referer}}", "latency": "{{.Response.Latency}}s", "protocol": "{{.Request.Proto}}"}, "traceId": "{{index .Request.Header "X-B3-Traceid"}}"}'
  manifests:
    - URL: https://github.com/knative/eventing/releases/download/v0.21.0/eventing-sugar-controller.yaml
    - URL: https://github.com/knative/eventing/releases/download/v0.21.0/in-memory-channel.yaml
    - URL: https://github.com/knative/eventing/releases/download/v0.21.0/eventing.yaml
    - URL: https://github.com/knative/eventing/releases/download/v0.21.0/mt-channel-broker.yaml
  resources: {}
```

And here is the status:

```yaml
status:
  conditions:
  - lastTransitionTime: "2021-08-31T15:28:49Z"
    status: Unknown
    type: DependenciesInstalled
  - lastTransitionTime: "2021-08-31T15:28:49Z"
    status: Unknown
    type: DeploymentsAvailable
  - lastTransitionTime: "2021-08-31T15:28:49Z"
    status: Unknown
    type: InstallSucceeded
  - lastTransitionTime: "2021-08-31T15:28:49Z"
    status: Unknown
    type: Ready
  - lastTransitionTime: "2021-08-31T15:28:49Z"
    status: "True"
    type: VersionMigrationEligible
```

Here is the log
```log
{"severity":"ERROR","timestamp":"2021-08-31T15:31:58.6490755Z","logger":"knative-operator","caller":"knativeserving/reconciler.go:305","message":"Returned an error","knative.dev/pod":"knative-operator-65fc986fc4-hcd57","knative.dev/controller":"knative.dev.operator.pkg.reconciler.knativeserving.Reconciler","knative.dev/kind":"operator.knative.dev.KnativeServing","knative.dev/traceid":"bab0a7da-73a3-401e-aac5-7211a2482c89","knative.dev/key":"knative-serving/knative-serving","targetMethod":"ReconcileKind","error":"stat /var/run/ko/ingress/0.21: no such file or directory","stacktrace":"knative.dev/operator/pkg/client/injection/reconciler/operator/v1alpha1/knativeserving.(*reconcilerImpl).Reconcile\n\tknative.dev/operator/pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/reconciler.go:305\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210803160015-21eb4c167cc5/controller/controller.go:540\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210803160015-21eb4c167cc5/controller/controller.go:477"}
{"severity":"ERROR","timestamp":"2021-08-31T15:31:58.6492703Z","logger":"knative-operator","caller":"controller/controller.go:564","message":"Reconcile error","knative.dev/pod":"knative-operator-65fc986fc4-hcd57","knative.dev/controller":"knative.dev.operator.pkg.reconciler.knativeserving.Reconciler","knative.dev/kind":"operator.knative.dev.KnativeServing","duration":"2.5438512s","error":"stat /var/run/ko/ingress/0.21: no such file or directory","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20210803160015-21eb4c167cc5/controller/controller.go:564\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210803160015-21eb4c167cc5/controller/controller.go:541\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210803160015-21eb4c167cc5/controller/controller.go:477"}
{"severity":"INFO","timestamp":"2021-08-31T15:31:58.6497931Z","logger":"knative-operator.event-broadcaster","caller":"record/event.go:282","message":"Event(v1.ObjectReference{Kind:\"KnativeServing\", Namespace:\"knative-serving\", Name:\"knative-serving\", UID:\"aebf2149-8428-4d97-80d5-1e8bcc083f55\", APIVersion:\"operator.knative.dev/v1alpha1\", ResourceVersion:\"4589\", FieldPath:\"\"}): type: 'Warning' reason: 'InternalError' stat /var/run/ko/ingress/0.21: no such file or directory","knative.dev/pod":"knative-operator-65fc986fc4-hcd57"}
```

> The KnativeServing yaml without manifests works run as I test.
