### ISSUE TITLE
`spec.deployments.replicas` does not take care about HorizontalPodAutoscaler

### ISSUE THREAD

**Issue by nak3** [knative/operator#762]
We can overrides `spec.deployments.replicas` as:

```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: ks
  namespace: knative-serving
spec:
  deployments:
  - name: webhook
    replicas: 3
```

But it does not change the values in `HorizontalPodAutoscaler`:

https://github.com/knative/operator/blob/f4ce4ff51a7fe3f6941073c7733a2e83f8b7faf1/pkg/reconciler/common/deployments_override.go#L86-L90

Some deployments (e.g. webhook, activator) deploys HPA so we need to change the values.

https://github.com/knative/operator/blob/f4ce4ff51a7fe3f6941073c7733a2e83f8b7faf1/cmd/operator/kodata/knative-serving/0.25.1/2-serving-core.yaml#L5435

**Comment by matzew** [comment]
@nak3 we have some code updating the HPA `minReplica` here: https://github.com/knative/operator/blob/main/pkg/reconciler/common/ha.go#L76-L89

I think we should do something similar on the `deployments_override.go` file, to check for both: `min` and `max`...

**Comment by maschmid** [comment]
I think we need an explicit option like
```
spec:
  horizontalPodAutoscalers:
  - name: foo
    minReplicas: ...
    maxReplicas: ...
```

+ a warning if one attempts to set spec.deployments[].replicas for something the operator does deploy an HPA...
