### ISSUE TITLE
knative-serving installed via the operator fails to reconcile service revisions

### ISSUE THREAD

**Issue by gvmw** [knative/operator#789]
**Describe the bug**

[Deploying your first Knative Service](https://knative.dev/docs/getting-started/first-service/) never completes when knative-serving has been installed via the knative-operator. The error is:

```
NAME                                          READY   STATUS    RESTARTS   AGE
pod/hello-world-deployment-858c8964dc-jlrzp   2/2     Running   0          6s

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/hello-world-deployment   1/1     1            1           7s

NAME                                                DESIRED   CURRENT   READY   AGE
replicaset.apps/hello-world-deployment-858c8964dc   1         1         1       7s

NAME                                      LATESTCREATED   LATESTREADY   READY     REASON
configuration.serving.knative.dev/hello   hello-world                   Unknown

NAME                                URL                                           LATESTCREATED   LATESTREADY   READY     REASON
service.serving.knative.dev/hello   http://hello.cloudevents-player.example.com   hello-world                   Unknown   RevisionMissing

NAME                                       CONFIG NAME   K8S SERVICE NAME   GENERATION   READY     REASON   ACTUAL REPLICAS   DESIRED REPLICAS
revision.serving.knative.dev/hello-world   hello         hello-world        1            Unknown

NAME                              URL                                           READY     REASON
route.serving.knative.dev/hello   http://hello.cloudevents-player.example.com   Unknown   RevisionMissing
```

**Expected behavior**

I would expect the following result when installing my first knative service:

```
NAME                          TYPE           CLUSTER-IP      EXTERNAL-IP                            PORT(S)                                      AGE
service/hello                 ExternalName   <none>          hello.cloudevents-player.example.com   80/TCP                                       5m11s
service/hello-world           ClusterIP      10.27.243.161   <none>                                 80/TCP                                       5m13s
service/hello-world-private   ClusterIP      10.27.251.218   <none>                                 80/TCP,9090/TCP,9091/TCP,8022/TCP,8012/TCP   5m13s

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/hello-world-deployment   0/0     0            0           5m13s

NAME                                               DESIRED   CURRENT   READY   AGE
replicaset.apps/hello-world-deployment-c6984c767   0         0         0       5m13s

NAME                              URL                                           READY     REASON
route.serving.knative.dev/hello   http://hello.cloudevents-player.example.com   Unknown   IngressNotConfigured

NAME                                      LATESTCREATED   LATESTREADY   READY   REASON
configuration.serving.knative.dev/hello   hello-world     hello-world   True    

NAME                                       CONFIG NAME   K8S SERVICE NAME   GENERATION   READY   REASON   ACTUAL REPLICAS   DESIRED REPLICAS
revision.serving.knative.dev/hello-world   hello         hello-world        1            True             0                 0

NAME                                URL                                           LATESTCREATED   LATESTREADY   READY     REASON
service.serving.knative.dev/hello   http://hello.cloudevents-player.example.com   hello-world     hello-world   Unknown   IngressNotConfigured
```

**To Reproduce**

In GKE v1.20.10-gke.1600

Install knative-operator:

```
kubectl apply --filename https://github.com/knative/operator/releases/latest/download/operator.yaml
```

Install knative-serving:

```
kubectl apply --filename - <<EOF
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
EOF
```

Install first knative service:

```
kubectl apply --filename - <<EOF
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    metadata:
      # This is the name of our new "Revision," it must follow the convention {service-name}-{revision-name}
      name: hello-world
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
EOF
```

We (+@benmoss) have confirmed that this is also happening on Kind v0.11.1 running K8s v1.22.1.

**Knative release version**

v0.25.1

**Additional context**

[Installing knative-serving with YAML](https://knative.dev/docs/admin/install/serving/install-serving-with-yaml/#install-the-knative-serving-component) works as expected. That's the workaround that we ended up with.

**Comment by markusthoemmes** [comment]
can you please confirm the Knative Serving version installed here? Only 0.25.1 is compatible with 1.22 and that has been released with the Operator version 0.25.2.

**Comment by benmoss** [comment]
On GKE this was k8s 1.20.10, so it's not due to 1.22. I don't have the cluster anymore and trying to reproduce on kind now I'm getting

```
Normal   FinalizerUpdate  14s   knativeserving-controller  Updated "knative-serving" finalizers
  Warning  InternalError    4s    knativeserving-controller  please install istio or disable the istio ingress plugin: no matches for kind "Gateway" in version "networking.istio.io/v1alpha3
```

**Comment by benmoss** [comment]
Ah, I think this is the underlying issue. I don't think we'd noticed that the knativeserving object was in a failed state.

**Comment by gvmw** [comment]
I have just followed the steps described in the issue and I'm seeing the same behaviour.

This was on a freshly deployed K8s 1.20 running on GKE with Knative Serving `serving.knative.dev/release=v0.26.0` installed via Knative Operator `app.kubernetes.io/version=0.26.1`

**Comment by gvmw** [comment]
I think that @benmoss was saying that the issue was a missing Knative networking layer (e.g.  Kourier / Contour / Istio etc.). As an aside, I have found this wording odd, because 

In practice, if I start with a freshly deployed K8s 1.20 on GKE, and follow these exact steps:

```
kubectl apply --filename https://github.com/knative/serving/releases/download/v0.26.0/serving-crds.yaml
kubectl apply --filename https://github.com/knative/serving/releases/download/v0.26.0/serving-core.yaml
kubectl apply --filename - <<EOF
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    metadata:
      # This is the name of our new "Revision," it must follow the convention {service-name}-{revision-name}
      name: hello-world
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
EOF
```

The hello Knative service fails with the expected error:

```
Name:         hello
Namespace:    default
API Version:  serving.knative.dev/v1
Kind:         Service
Metadata:
  Creation Timestamp:  2021-10-01T13:04:26Z
  Generation:          1
# ...
Spec:
  Template:
    Metadata:
      Name:                hello-world
    Spec:
      Container Concurrency:  0
      Containers:
        Env:
          Name:   TARGET
          Value:  World
        Image:    gcr.io/knative-samples/helloworld-go
        Name:     user-container
        Ports:
          Container Port:  8080
          Protocol:        TCP
        Readiness Probe:
          Success Threshold:  1
          Tcp Socket:
            Port:  0
        Resources:
      Enable Service Links:  false
      Timeout Seconds:       300
  Traffic:
    Latest Revision:  true
    Percent:          100
Status:
  Address:
    URL:  http://hello.default.svc.cluster.local
  Conditions:
    Last Transition Time:        2021-10-01T13:04:52Z
    Status:                      True
    Type:                        ConfigurationsReady
    Last Transition Time:        2021-10-01T13:04:52Z
    Message:                     Ingress has not yet been reconciled.
    Reason:                      IngressNotConfigured
    Status:                      Unknown
    Type:                        Ready
    Last Transition Time:        2021-10-01T13:04:52Z
    Message:                     Ingress has not yet been reconciled.
    Reason:                      IngressNotConfigured
    Status:                      Unknown
    Type:                        RoutesReady
  Latest Created Revision Name:  hello-world
  Latest Ready Revision Name:    hello-world
  Observed Generation:           1
  Traffic:
    Latest Revision:  true
    Percent:          100
    Revision Name:    hello-world
  URL:                http://hello.default.example.com
Events:
  Type    Reason   Age   From                Message
  ----    ------   ----  ----                -------
  Normal  Created  32m   service-controller  Created Configuration "hello"
  Normal  Created  32m   service-controller  Created Route "hello"
```

I don't want to drag this out as I have my fix - install from YAML, don't use the Operator - so I'm going to close this issue and leave these comments here in case they help someone else 👋🏻
