### ISSUE TITLE
v0.26.2 has kodata for Eventing v0.26.1, but fails to install it

### ISSUE THREAD

**Issue by antoineco** [knative/operator#825]
**Describe the bug**

The following manifest:

```yaml
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
spec:
  version: 0.26.1

  source:
    github:
      enabled: true
    gitlab:
      enabled: true
    kafka:
      enabled: true
```

yields the following error:

```
Events:
  Type     Reason         Age                 From                        Message
  ----     ------         ----                ----                        -------
  Warning  InternalError  12m (x16 over 15m)  knativeeventing-controller  The manifests of the target version 0.26.1 are not available to this release.
```

**Comment by houshengbo** [comment]
@antoineco 

I just tried 0.26.2 operator and applied the following CR. It did not break. I am not sure how to reproduce this issue.
What is the kubernetes version u are using? Do you have existing knative eventing installed?

```
cat <<-EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
 name: knative-eventing
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  version: 0.26.1
  source:
    github:
      enabled: true
    gitlab:
      enabled: true
    kafka:
```
