### ISSUE TITLE
Dynamic knative-local-gateway service selectors

### ISSUE THREAD

**Issue by MMartyn** [knative/operator#831]
**Describe the bug**
If update the knative-local-gateway selectors, the service isn't updated as well to the new selectors 
```
  ingress:
    istio:
      enabled: true
      knative-local-gateway:
        selector:
          app: custom-gateway
```

**Expected behavior**
I am not sure if it is the wrong expectation, but I would have expected the knative-local-gateway service in the istio-system namespace would get updated with the same selectors.

**To Reproduce**
Set selector overrides on the knative-local-gateway

**Knative release version**
0.25
