### ISSUE TITLE
Heartbeats resources don't come up after using the Eventing operator

### ISSUE THREAD

**Issue by JamesMcMahon** [knative/operator#847]
**Describe the bug**
Following the instructions at https://knative.dev/docs/admin/install/knative-with-operators/#installing-the-knative-eventing-component.

I end up with the following broken resources, (non-broken omitted for clarity)

```
NAME                                                           READY   STATUS             RESTARTS   AGE
pod/heartbeats-source-deployment-64dff6896d-lqslh              0/1     CrashLoopBackOff   255        21h

NAME                                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/heartbeats-source-deployment   0/1     1            0           21h

NAME                                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/heartbeats-source-deployment-64dff6896d   1         1         0       21h

NAME                                                    SINK   AGE   READY   REASON
containersource.sources.knative.dev/heartbeats-source          21h   False   MinimumReplicasUnavailable

NAME                                                            SINK   AGE   READY   REASON
sinkbinding.sources.knative.dev/heartbeats-source-sinkbinding          21h   False   NoURI
```

Logs for the broken pod,

```
2021/10/29 17:03:08 Failed to read tracing config, using the no-op default: empty json tracing config
2021/10/29 17:03:08 failed to create client: http target option was empty string
```

Describing the sinkbinding source shows the following status,

```yaml
Status:
  Conditions:
    Last Transition Time:  2021-10-28T19:31:47Z
    Message:               URI could not be extracted from destination
    Reason:                NoURI
    Status:                False
    Type:                  Ready
    Last Transition Time:  2021-10-28T19:31:47Z
    Status:                Unknown
    Type:                  SinkProvided
```

**Expected behavior**
The resources should be brought up by the operator. If additional config or setup is needed it should be documented.

**To Reproduce**
Kubectl applying the following
```
apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
```

**Knative release version**
```
NAME               VERSION   READY   REASON
knative-eventing   0.26.0    True
````

**Additional context**
Add any other context about the problem here such as proposed priority
