### ISSUE TITLE
"controller" resources configuration overlap between "controller" and "net-istio-controller"

### ISSUE THREAD

**Issue by treyhyde** [knative/operator#860]
**Describe the bug**

https://knative.dev/docs/install/operator/configuring-serving-cr/#system-resource-settings
indicates

```Requests and limits can be configured for the following containers: activator, autoscaler, controller, webhook, autoscaler-hpa, net-istio-controller and queue-proxy.```

When in fact, net-istio-controller does not work (as in applying resources changes).   It has a container called 'controller' and not 'net-istio-controller'.

If you add a resources section for `controller` as in

```  
- container: controller
    limits:
      cpu: 300m
      memory: 1000Mi
    requests:
      cpu: 30m
      memory: 800Mi
```

it will apply the new resource to the `controller` deployment in addition to `net-istio-controller` which is undesirable. 

**Expected behavior**

Behavior as documented that would allow `net-istio-controller` and `controller` to have resources adjusted independently. 

**To Reproduce**

Try to change resources for `net-istio-controller` as described in the CR document above.

**Knative release version**
0.26

**Additional context**
N/A

**Comment by nak3** [comment]
I agree that it is a bug.
This is a same concern with https://github.com/knative/operator/issues/382#issuecomment-741002226
I also proposed the PR to override the resource under `spec.deployments.containers` before but it was rejected as https://github.com/knative/operator/pull/472#issuecomment-779380630

**Comment by jasmdk** [comment]
Related to this, I try to set the images to point to a local registry to use the operator in airgapped mode using the registry.override: https://github.com/knative/operator/blob/main/docs/configuration.md#specregistry
When I set the image for "controller" or "webhook", they apply to both the "controller" and the "net-istio-controller" probably because they both use "controller" as their container name.
The same goes for "webhook" and "net-istio-webhook".
This means I have no way to use this in an airgapped environment.

**Comment by houshengbo** [comment]
@treyhyde @nak3 
I just verified with the 1.0 release. It seems to work with both of the controller and net-istio-controller at the same time.

When I applied the CR as below:
```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  resources:
  - container: controller
    requests:
      cpu: 400m
      memory: 200Mi
    limits:
      cpu: 500m
      memory: 300Mi
```

Both of the requests and limits in controller and net-istio-controller were updated, as controller is their container's name.
