### ISSUE TITLE
registry override change  queue-proxy image  not update  config-deployment  configmap after finished install

### ISSUE THREAD

**Issue by wu0407** [knative/operator#918]
**Describe the bug** 
Add  `queue-proxy` registry override after knative serving finished, but  operator not update `queueSidecarImage` in `config-deployment`  configmap.

**Expected behavior**
operator change  `queueSidecarImage` in `config-deployment`  configmap.

**To Reproduce**
Steps to reproduce the behavior.
knative-serving.yaml
```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative
spec:
  registry:
    override:
       activator: xxx.com/k8s/knative-activator:v1.1.0
       autoscaler: xxx.com/k8s/knative-autoscaler:v1.1.0
       autoscaler-hpa: xxx.com/k8s/knative-autoscaler-hpa:v1.1.0
       controller: xxx.com/k8s/knative-controller:v1.1.0
       domain-mapping: xxxx.com/k8s/knative-domain-mapping:v1.1.0
       domainmapping-webhook: xxxx.com/k8s/knative-domain-mapping-webhook:v1.1.0
       net-istio-controller/controller: xxx.com/k8s/knative-net-istio-controller:v1.1.0
       net-istio-webhook/webhook: xxxx.com/k8s/knative-net-istio-webhook:v1.1.0
       migrate: xxx.com/k8s/knative-apiextensions-storageversion-migrate:v1.1.0
       webhook: xxx.com/k8s/knative-serving-webhook:v1.1.0
```
1. apply knative-serving.yaml, wait operator finished install knative serving components.
2. add `queue-proxy` registry override
 ```
     queue-proxy: xxx.com/k8s/knative-queue:v1.1.0
 ```
3. kubectl get configmaps -n knative config-deployment -o yaml

**Knative release version**
The Knative version, where you find this issue.
v1.1.0

**Additional context**
Add any other context about the problem here such as proposed priority

**Comment by wu0407** [comment]
To change `queueSidecarImage` or `queue-sidecar-image` in current version, need configure `spec.config.deployment`  in KnativeServing operator
```
config:
    deployment:
      queue-sidecar-image: xxxx.com/k8s/knative-queue:v1.1.0
      queueSidecarImage: xxx.com/k8s/knative-queue:v1.1.0
```
